// Alle skill_keys in Prod, Stand 04.10.2026 (dbread: select skill_key from skills).
// Nur von Tests importiert: inhaltsbereiche.test.ts prüft, dass jeder davon in
// einem benannten Inhaltsbereich landet. Neue Knoten -> Liste neu ziehen.

export const SKILL_BESTAND: readonly string[] = [
  'bruch_add', 'bruch_dezimal', 'bruch_div', 'bruch_kuerzen', 'bruch_mult', 'dezimal_add_sub',
  'dezimal_div', 'dezimal_mult', 'fkt_exp_anwendung', 'fkt_exp_gleichung', 'fkt_exp_halbwert',
  'fkt_exp_term', 'fkt_exp_wachstum', 'fkt_linear_gleichung', 'fkt_linear_graph',
  'fkt_linear_nullstelle', 'fkt_linear_steigung', 'fkt_linear_yabschnitt', 'fkt_quadr_extrem',
  'fkt_quadr_normalform', 'fkt_quadr_nullstellen', 'fkt_quadr_parabel', 'fkt_quadr_scheitel',
  'fkt_sinus_bogenmass', 'fkt_sinus_einheitskreis', 'fkt_sinus_graph', 'fkt_sinus_parameter',
  'fkt_sinus_periodisch', 'geo_aehnlich_flaeche', 'geo_aehnlich_strahlen_abschnitt',
  'geo_aehnlich_strahlen_parallel', 'geo_aehnlich_streckfaktor', 'geo_flaeche_drachen_raute',
  'geo_flaeche_dreieck', 'geo_flaeche_rechteck', 'geo_flaeche_rueck', 'geo_flaeche_term',
  'geo_flaeche_trapez', 'geo_flaeche_zusammengesetzt', 'geo_koerper_kegel', 'geo_koerper_kugel',
  'geo_koerper_prisma', 'geo_koerper_pyramide', 'geo_koerper_zylinder', 'geo_koordinaten',
  'geo_kreis_flaeche', 'geo_kreis_rueck', 'geo_kreis_sektor', 'geo_kreis_umfang',
  'geo_kreis_zusammen', 'geo_massstab', 'geo_pythagoras_abstand', 'geo_pythagoras_anwendung',
  'geo_pythagoras_hypotenuse', 'geo_pythagoras_kathete', 'geo_pythagoras_umkehrung',
  'geo_trigo_anwendung', 'geo_trigo_kosinussatz', 'geo_trigo_seite', 'geo_trigo_verhaeltnis',
  'geo_trigo_winkel', 'geo_umfang', 'geo_volumen_quader', 'geo_winkel_dreieck',
  'geo_winkel_neben_scheitel', 'geo_winkel_parallelen', 'geo_winkel_summe', 'geo_winkel_thales',
  'gleichung_beidseitig', 'gleichung_einschrittig', 'gleichung_lgs_addition',
  'gleichung_lgs_einsetzen', 'gleichung_lgs_gleichsetzen', 'gleichung_lgs_grafisch',
  'gleichung_lgs_sachaufgabe', 'gleichung_modellieren', 'gleichung_neg_koeffizient',
  'gleichung_quadr_anzahl', 'gleichung_quadr_faktor', 'gleichung_quadr_formel',
  'gleichung_quadr_wurzel', 'gleichung_zweischrittig', 'groessen_flaechen', 'groessen_gemischt',
  'groessen_laengen', 'groessen_massen', 'groessen_volumen', 'groessen_zeit', 'potenzen',
  'proportionalitaet', 'prozent_grundwert', 'prozent_prozentsatz', 'prozent_prozentwert',
  'prozent_veraenderung', 'prozent_zins_jahreszins', 'prozent_zins_rueckrechnung',
  'prozent_zins_teilzins', 'prozent_zins_zinseszins', 'runden_ueberschlag',
  'stoch_bedingt_irrefuehrend', 'stoch_bedingt_umkehr', 'stoch_bedingt_unabhaengig',
  'stoch_bedingt_vierfeld', 'stoch_bedingt_wkeit', 'stoch_gegenereignis', 'stoch_kenngroessen',
  'stoch_laplace', 'stoch_pfad_produkt', 'stoch_pfad_summe', 'term_ausklammern',
  'term_ausmultiplizieren', 'term_binom_faktorisieren', 'term_binom_gemischt',
  'term_binom_quadrat', 'term_binom_quadratdifferenz', 'term_einsetzen', 'term_minusklammer',
  'term_zusammenfassen', 'vorzeichen_add_sub', 'vorzeichen_mult_div', 'vorzeichen_vorrang',
  'zahl_potenz_gesetze', 'zahl_potenz_negativ', 'zahl_potenz_rechnen', 'zahl_potenz_zehner',
  'zahl_wurzel_gesetze', 'zahl_wurzel_irrational', 'zahl_wurzel_naeherung', 'zahl_wurzel_quadrat',
  'zahl_wurzel_teilweise',
]
