// Screening-Item-Entwürfe — Klasse 8, Cluster "Algebra & Funktionen".
// Versioniert (PR-Review) + via scripts/seed-screening-items.ts mit
// active=false geseedet; fachliche Freigabe via /admin/screening-items.
// Autogradebar: NUMERIC (canonical {value:Zahl}) | MC (canonical {index}).

import type { SeedItem } from './zahl-rechnen'

const C = 'Algebra & Funktionen'
const G = 8

export const ALGEBRA_FUNKTIONEN_ITEMS: SeedItem[] = [
  // ── Terme zusammenfassen (Wert einsetzen → NUMERIC) ────────────────────
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_term_vereinfachen', skill_label: 'Terme zusammenfassen', level: 1, curriculum_seq: 40, input_type: 'NUMERIC', prompt: 'Vereinfache 2x + 3x und setze x = 4 ein. Ergebnis?', payload: null, canonical: { value: 20 }, check_type: 'numeric', tolerance: 0, typical_errors: ['x mitgezählt: 5x4=…', 'nicht zusammengefasst'], explanation: '2x+3x = 5x; 5·4 = 20.' },
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_term_vereinfachen', skill_label: 'Terme zusammenfassen', level: 2, curriculum_seq: 40, input_type: 'NUMERIC', prompt: 'Vereinfache 3a + 2 - a + 5 und setze a = 3 ein. Ergebnis?', payload: null, canonical: { value: 13 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Konstanten nicht addiert', 'Vorzeichen -a falsch'], explanation: '3a-a+2+5 = 2a+7; 2·3+7 = 13.' },
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_term_vereinfachen', skill_label: 'Terme zusammenfassen', level: 3, curriculum_seq: 40, input_type: 'NUMERIC', prompt: 'Vereinfache 4(x+2) - 2x und setze x = 5 ein. Ergebnis?', payload: null, canonical: { value: 18 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Distributivgesetz unvollständig', 'nur 4·x'], explanation: '4x+8-2x = 2x+8; 2·5+8 = 18.' },

  // ── Klammern auflösen (1× MC) ──────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_klammer', skill_label: 'Klammern auflösen (Distributivgesetz)', level: 1, curriculum_seq: 41, input_type: 'MC', prompt: 'Welcher Term ist äquivalent zu 2(x + 3)?', payload: { type: 'mc', options: ['2x + 3', '2x + 6', 'x + 6', '2x + 5'], correct_index: 1 }, canonical: { index: 1 }, check_type: 'mc_index', tolerance: null, typical_errors: ['nur ersten Summanden multipliziert'], explanation: '2·x + 2·3 = 2x + 6.' },
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_klammer', skill_label: 'Klammern auflösen (Distributivgesetz)', level: 2, curriculum_seq: 41, input_type: 'NUMERIC', prompt: 'Löse die Klammer auf und setze x = 2 ein: 3(x + 4). Ergebnis?', payload: null, canonical: { value: 18 }, check_type: 'numeric', tolerance: 0, typical_errors: ['3x+4 statt 3x+12'], explanation: '3x+12; 3·2+12 = 18.' },
  { cluster_name: C, class_level: G, topic: 'Terme', skill_code: 'af_klammer', skill_label: 'Klammern auflösen (Distributivgesetz)', level: 3, curriculum_seq: 41, input_type: 'NUMERIC', prompt: 'Vereinfache und setze x = 3 ein: 5(x - 1) - 2(x + 2). Ergebnis?', payload: null, canonical: { value: 0 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Vorzeichen bei -2(x+2)'], explanation: '5x-5-2x-4 = 3x-9; 3·3-9 = 0.' },

  // ── Lineare Gleichungen (einfach) ──────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_einfach', skill_label: 'Lineare Gleichung lösen (einfach)', level: 1, curriculum_seq: 45, input_type: 'NUMERIC', prompt: 'Löse: x + 5 = 12. x = ?', payload: null, canonical: { value: 7 }, check_type: 'numeric', tolerance: 0, typical_errors: ['17'], explanation: 'x = 12 - 5 = 7.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_einfach', skill_label: 'Lineare Gleichung lösen (einfach)', level: 2, curriculum_seq: 45, input_type: 'NUMERIC', prompt: 'Löse: 3x = 21. x = ?', payload: null, canonical: { value: 7 }, check_type: 'numeric', tolerance: 0, typical_errors: ['63'], explanation: 'x = 21 : 3 = 7.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_einfach', skill_label: 'Lineare Gleichung lösen (einfach)', level: 3, curriculum_seq: 45, input_type: 'NUMERIC', prompt: 'Löse: 4x - 7 = 9. x = ?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Reihenfolge der Umformungen'], explanation: '4x = 16 → x = 4.' },

  // ── Gleichungen mit Klammern ───────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_klammer', skill_label: 'Gleichung mit Klammern lösen', level: 1, curriculum_seq: 46, input_type: 'NUMERIC', prompt: 'Löse: 2(x + 1) = 10. x = ?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Klammer nicht aufgelöst'], explanation: '2x+2=10 → x=4.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_klammer', skill_label: 'Gleichung mit Klammern lösen', level: 2, curriculum_seq: 46, input_type: 'NUMERIC', prompt: 'Löse: 3(x - 2) = 9. x = ?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['-6 nicht beachtet'], explanation: '3x-6=9 → x=5.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_klammer', skill_label: 'Gleichung mit Klammern lösen', level: 3, curriculum_seq: 46, input_type: 'NUMERIC', prompt: 'Löse: 2(x + 3) = 4x - 2. x = ?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Variablen falsch sortiert'], explanation: '2x+6=4x-2 → 8=2x → x=4.' },

  // ── Gleichungen mit Brüchen ────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_bruch', skill_label: 'Gleichung mit Brüchen lösen', level: 1, curriculum_seq: 47, input_type: 'NUMERIC', prompt: 'Löse: x/2 = 6. x = ?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['3'], explanation: 'x = 6·2 = 12.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_bruch', skill_label: 'Gleichung mit Brüchen lösen', level: 2, curriculum_seq: 47, input_type: 'NUMERIC', prompt: 'Löse: x/3 + 1 = 4. x = ?', payload: null, canonical: { value: 9 }, check_type: 'numeric', tolerance: 0, typical_errors: ['zuerst ·3 statt -1'], explanation: 'x/3=3 → x=9.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Gleichungen', skill_code: 'af_gl_bruch', skill_label: 'Gleichung mit Brüchen lösen', level: 3, curriculum_seq: 47, input_type: 'NUMERIC', prompt: 'Löse: (x + 2)/2 = 5. x = ?', payload: null, canonical: { value: 8 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur x+2=5'], explanation: 'x+2=10 → x=8.' },

  // ── Steigung ───────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_steigung', skill_label: 'Steigung bestimmen', level: 1, curriculum_seq: 50, input_type: 'NUMERIC', prompt: 'Die Funktion y = 3x + 2. Wie groß ist die Steigung?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['2 (y-Abschnitt)'], explanation: 'Steigung m = 3.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_steigung', skill_label: 'Steigung bestimmen', level: 2, curriculum_seq: 50, input_type: 'NUMERIC', prompt: 'Eine Gerade verläuft durch (0|1) und (2|7). Steigung?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Δx und Δy vertauscht'], explanation: 'm = (7-1)/(2-0) = 3.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_steigung', skill_label: 'Steigung bestimmen', level: 3, curriculum_seq: 50, input_type: 'NUMERIC', prompt: 'Eine Gerade verläuft durch (1|4) und (4|-5). Steigung?', payload: null, canonical: { value: -3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Vorzeichen', 'Δ falsch herum'], explanation: 'm = (-5-4)/(4-1) = -9/3 = -3.' },

  // ── y-Achsenabschnitt ──────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_yabschnitt', skill_label: 'y-Achsenabschnitt bestimmen', level: 1, curriculum_seq: 51, input_type: 'NUMERIC', prompt: 'y = 2x + 5. y-Achsenabschnitt?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['2 (Steigung)'], explanation: 'b = 5.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_yabschnitt', skill_label: 'y-Achsenabschnitt bestimmen', level: 2, curriculum_seq: 51, input_type: 'NUMERIC', prompt: 'y = -3x - 4. y-Achsenabschnitt?', payload: null, canonical: { value: -4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['+4'], explanation: 'b = -4.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_yabschnitt', skill_label: 'y-Achsenabschnitt bestimmen', level: 3, curriculum_seq: 51, input_type: 'NUMERIC', prompt: 'Eine Gerade hat Steigung 4 und verläuft durch (0|-2). y-Achsenabschnitt?', payload: null, canonical: { value: -2 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Steigung als Abschnitt'], explanation: 'Punkt (0|-2) → b = -2.' },

  // ── Funktionswert ──────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_fwert', skill_label: 'Funktionswert berechnen', level: 1, curriculum_seq: 52, input_type: 'NUMERIC', prompt: 'f(x) = 2x + 1. Berechne f(3).', payload: null, canonical: { value: 7 }, check_type: 'numeric', tolerance: 0, typical_errors: ['2·3 ohne +1'], explanation: 'f(3) = 2·3+1 = 7.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_fwert', skill_label: 'Funktionswert berechnen', level: 2, curriculum_seq: 52, input_type: 'NUMERIC', prompt: 'f(x) = -x + 5. Berechne f(4).', payload: null, canonical: { value: 1 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Vorzeichen von -x'], explanation: 'f(4) = -4+5 = 1.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_fwert', skill_label: 'Funktionswert berechnen', level: 3, curriculum_seq: 52, input_type: 'NUMERIC', prompt: 'f(x) = 3x - 7. Für welches x ist f(x) = 8? x = ?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur 3x=8'], explanation: '3x-7=8 → 3x=15 → x=5.' },

  // ── Nullstelle ─────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_nullstelle', skill_label: 'Nullstelle bestimmen', level: 1, curriculum_seq: 53, input_type: 'NUMERIC', prompt: 'Nullstelle von y = x - 4? x = ?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['-4'], explanation: 'x-4=0 → x=4.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_nullstelle', skill_label: 'Nullstelle bestimmen', level: 2, curriculum_seq: 53, input_type: 'NUMERIC', prompt: 'Nullstelle von y = 2x - 6? x = ?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['6'], explanation: '2x-6=0 → x=3.' },
  { cluster_name: C, class_level: G, topic: 'Lineare Funktionen', skill_code: 'af_nullstelle', skill_label: 'Nullstelle bestimmen', level: 3, curriculum_seq: 53, input_type: 'NUMERIC', prompt: 'Nullstelle von y = -3x + 9? x = ?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Vorzeichen bei -3x'], explanation: '-3x+9=0 → x=3.' },

  // ── Textaufgabe → Gleichung ────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Textaufgaben', skill_code: 'af_text', skill_label: 'Textaufgabe in Gleichung übersetzen', level: 1, curriculum_seq: 55, input_type: 'NUMERIC', prompt: 'Eine Zahl plus 7 ergibt 12. Wie heißt die Zahl?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['19'], explanation: 'x+7=12 → x=5.' },
  { cluster_name: C, class_level: G, topic: 'Textaufgaben', skill_code: 'af_text', skill_label: 'Textaufgabe in Gleichung übersetzen', level: 2, curriculum_seq: 55, input_type: 'NUMERIC', prompt: 'Das Doppelte einer Zahl ist 18. Wie heißt die Zahl?', payload: null, canonical: { value: 9 }, check_type: 'numeric', tolerance: 0, typical_errors: ['36'], explanation: '2x=18 → x=9.' },
  { cluster_name: C, class_level: G, topic: 'Textaufgaben', skill_code: 'af_text', skill_label: 'Textaufgabe in Gleichung übersetzen', level: 3, curriculum_seq: 55, input_type: 'NUMERIC', prompt: 'Verdreifacht und um 4 vermehrt ergibt eine Zahl 19. Wie heißt die Zahl?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Reihenfolge / 19:3'], explanation: '3x+4=19 → 3x=15 → x=5.' },
]
