// Screening-Item-Entwürfe — Klasse 8, Cluster "Daten & Zufall".
// Versioniert (PR-Review) + via scripts/seed-screening-items.ts mit
// active=false geseedet; Freigabe via /admin/screening-items.
// Autogradebar: NUMERIC (canonical {value}) | normalized (gekürzter
// Bruch "a/b"). Datensätze sind im Text explizit angegeben (kein Bild).

import type { SeedItem } from './zahl-rechnen'

const C = 'Daten & Zufall'
const G = 8

export const DATEN_ZUFALL_ITEMS: SeedItem[] = [
  // ── Diagramm/Tabelle ablesen ───────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_ablesen', skill_label: 'Daten aus Tabelle/Diagramm ablesen', level: 1, curriculum_seq: 75, input_type: 'NUMERIC', prompt: 'Strichliste: Mo 3, Di 5, Mi 2. Wie viele insgesamt?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur größter Wert'], explanation: '3+5+2 = 10.' },
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_ablesen', skill_label: 'Daten aus Tabelle/Diagramm ablesen', level: 2, curriculum_seq: 75, input_type: 'NUMERIC', prompt: 'Säulen: A=12, B=8, C=20. Wie viel mehr hat C als B?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['C+B'], explanation: '20 − 8 = 12.' },
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_ablesen', skill_label: 'Daten aus Tabelle/Diagramm ablesen', level: 3, curriculum_seq: 75, input_type: 'NUMERIC', prompt: 'Werte: Mo 4, Di 6, Mi 5, Do 9, Fr 6. An wie vielen Tagen ≥ 6?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['> statt ≥'], explanation: 'Di, Do, Fr → 3 Tage.' },

  // ── Häufigkeit ─────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_haeufigkeit', skill_label: 'Absolute/relative Häufigkeit', level: 1, curriculum_seq: 76, input_type: 'NUMERIC', prompt: 'In 10 Würfen kam 4× „Kopf". Absolute Häufigkeit von Kopf?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['10−4'], explanation: 'Absolute Häufigkeit = 4.' },
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_haeufigkeit', skill_label: 'Absolute/relative Häufigkeit', level: 2, curriculum_seq: 76, input_type: 'NUMERIC', prompt: 'Bei 20 Beobachtungen kommt „rot" 5×. Relative Häufigkeit als Dezimalzahl?', payload: null, canonical: { value: 0.25 }, check_type: 'numeric', tolerance: 0, typical_errors: ['20/5'], explanation: '5/20 = 0,25.' },
  { cluster_name: C, class_level: G, topic: 'Daten', skill_code: 'dz_haeufigkeit', skill_label: 'Absolute/relative Häufigkeit', level: 3, curriculum_seq: 76, input_type: 'NUMERIC', prompt: 'Relative Häufigkeit 0,2 bei 50 Beobachtungen. Absolute Häufigkeit?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['50·0,02'], explanation: '0,2·50 = 10.' },

  // ── Mittelwert ─────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_mittelwert', skill_label: 'Arithmetisches Mittel', level: 1, curriculum_seq: 77, input_type: 'NUMERIC', prompt: 'Mittelwert von 4, 6, 8?', payload: null, canonical: { value: 6 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Summe 18'], explanation: '(4+6+8)/3 = 6.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_mittelwert', skill_label: 'Arithmetisches Mittel', level: 2, curriculum_seq: 77, input_type: 'NUMERIC', prompt: 'Mittelwert von 3, 7, 8, 10, 12?', payload: null, canonical: { value: 8 }, check_type: 'numeric', tolerance: 0, typical_errors: ['durch 4'], explanation: '40/5 = 8.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_mittelwert', skill_label: 'Arithmetisches Mittel', level: 3, curriculum_seq: 77, input_type: 'NUMERIC', prompt: 'Vier Werte haben Mittelwert 5. Drei davon: 3, 6, 4. Wie groß ist der vierte?', payload: null, canonical: { value: 7 }, check_type: 'numeric', tolerance: 0, typical_errors: ['5−13'], explanation: 'Summe = 20; 20−13 = 7.' },

  // ── Median ─────────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_median', skill_label: 'Median bestimmen', level: 1, curriculum_seq: 78, input_type: 'NUMERIC', prompt: 'Median von 2, 5, 9?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Mittelwert'], explanation: 'Mittlerer Wert = 5.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_median', skill_label: 'Median bestimmen', level: 2, curriculum_seq: 78, input_type: 'NUMERIC', prompt: 'Median von 3, 8, 1, 6, 4 (zuerst ordnen)?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nicht geordnet'], explanation: 'Geordnet 1,3,4,6,8 → Median 4.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_median', skill_label: 'Median bestimmen', level: 3, curriculum_seq: 78, input_type: 'NUMERIC', prompt: 'Median von 2, 4, 6, 10 (gerade Anzahl)?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur einen mittleren Wert'], explanation: '(4+6)/2 = 5.' },

  // ── Spannweite ─────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_spannweite', skill_label: 'Spannweite berechnen', level: 1, curriculum_seq: 79, input_type: 'NUMERIC', prompt: 'Spannweite von 3, 7, 5?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['max'], explanation: '7 − 3 = 4.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_spannweite', skill_label: 'Spannweite berechnen', level: 2, curriculum_seq: 79, input_type: 'NUMERIC', prompt: 'Spannweite von 12, 4, 9, 20, 7?', payload: null, canonical: { value: 16 }, check_type: 'numeric', tolerance: 0, typical_errors: ['20−7'], explanation: '20 − 4 = 16.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_spannweite', skill_label: 'Spannweite berechnen', level: 3, curriculum_seq: 79, input_type: 'NUMERIC', prompt: 'Die Spannweite ist 15, das Minimum 8. Wie groß ist das Maximum?', payload: null, canonical: { value: 23 }, check_type: 'numeric', tolerance: 0, typical_errors: ['15−8'], explanation: 'max = 8 + 15 = 23.' },

  // ── Modalwert ──────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_modus', skill_label: 'Modalwert bestimmen', level: 1, curriculum_seq: 80, input_type: 'NUMERIC', prompt: 'Modalwert von 2, 3, 3, 5?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Mittelwert'], explanation: 'Häufigster Wert = 3.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_modus', skill_label: 'Modalwert bestimmen', level: 2, curriculum_seq: 80, input_type: 'NUMERIC', prompt: 'Modalwert von 7, 1, 7, 4, 7, 2?', payload: null, canonical: { value: 7 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Anzahl 3'], explanation: '7 kommt am häufigsten.' },
  { cluster_name: C, class_level: G, topic: 'Lagemaße', skill_code: 'dz_modus', skill_label: 'Modalwert bestimmen', level: 3, curriculum_seq: 80, input_type: 'NUMERIC', prompt: 'Modalwert von 5, 5, 8, 8, 8, 2?', payload: null, canonical: { value: 8 }, check_type: 'numeric', tolerance: 0, typical_errors: ['5'], explanation: '8 erscheint 3×.' },

  // ── Laplace-Wahrscheinlichkeit (gekürzter Bruch) ───────────────────────
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_laplace', skill_label: 'Laplace-Wahrscheinlichkeit', level: 1, curriculum_seq: 81, input_type: 'NUMERIC', prompt: 'Würfel: Wahrscheinlichkeit für eine 3? Gekürzter Bruch (Form a/b).', payload: null, canonical: { value: '1/6' }, check_type: 'normalized', tolerance: null, typical_errors: ['1/3'], explanation: '1 von 6 → 1/6.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_laplace', skill_label: 'Laplace-Wahrscheinlichkeit', level: 2, curriculum_seq: 81, input_type: 'NUMERIC', prompt: 'Würfel: Wahrscheinlichkeit für eine gerade Zahl? Gekürzt (a/b).', payload: null, canonical: { value: '1/2' }, check_type: 'normalized', tolerance: null, typical_errors: ['3/6 nicht gekürzt'], explanation: '3/6 = 1/2.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_laplace', skill_label: 'Laplace-Wahrscheinlichkeit', level: 3, curriculum_seq: 81, input_type: 'NUMERIC', prompt: 'Urne: 2 rote, 3 blaue Kugeln. P(rot)? Gekürzt (a/b).', payload: null, canonical: { value: '2/5' }, check_type: 'normalized', tolerance: null, typical_errors: ['2/3'], explanation: '2 von 5 → 2/5.' },

  // ── Gegenwahrscheinlichkeit (gekürzter Bruch) ──────────────────────────
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_gegenwk', skill_label: 'Gegenwahrscheinlichkeit', level: 1, curriculum_seq: 82, input_type: 'NUMERIC', prompt: 'P(A) = 1/4. P(nicht A)? Gekürzt (a/b).', payload: null, canonical: { value: '3/4' }, check_type: 'normalized', tolerance: null, typical_errors: ['1−1=0'], explanation: '1 − 1/4 = 3/4.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_gegenwk', skill_label: 'Gegenwahrscheinlichkeit', level: 2, curriculum_seq: 82, input_type: 'NUMERIC', prompt: 'P(A) = 2/5. Gegenwahrscheinlichkeit? Gekürzt (a/b).', payload: null, canonical: { value: '3/5' }, check_type: 'normalized', tolerance: null, typical_errors: ['5/2'], explanation: '1 − 2/5 = 3/5.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_gegenwk', skill_label: 'Gegenwahrscheinlichkeit', level: 3, curriculum_seq: 82, input_type: 'NUMERIC', prompt: 'Würfel: P(keine 6)? Gekürzt (a/b).', payload: null, canonical: { value: '5/6' }, check_type: 'normalized', tolerance: null, typical_errors: ['1/6'], explanation: '1 − 1/6 = 5/6.' },

  // ── Relative Häufigkeit in Prozent ─────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_rel_prozent', skill_label: 'Relative Häufigkeit in Prozent', level: 1, curriculum_seq: 83, input_type: 'NUMERIC', prompt: '5 von 20 sind grün. Wie viel Prozent? (nur Zahl)', payload: null, canonical: { value: 25 }, check_type: 'numeric', tolerance: 0, typical_errors: ['20/5'], explanation: '5/20 = 25 %.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_rel_prozent', skill_label: 'Relative Häufigkeit in Prozent', level: 2, curriculum_seq: 83, input_type: 'NUMERIC', prompt: 'In 50 Würfen 30× „Zahl". Relative Häufigkeit in %? (nur Zahl)', payload: null, canonical: { value: 60 }, check_type: 'numeric', tolerance: 0, typical_errors: ['30'], explanation: '30/50 = 60 %.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_rel_prozent', skill_label: 'Relative Häufigkeit in Prozent', level: 3, curriculum_seq: 83, input_type: 'NUMERIC', prompt: 'Relative Häufigkeit 15 %, 200 Beobachtungen. Absolute Häufigkeit?', payload: null, canonical: { value: 30 }, check_type: 'numeric', tolerance: 0, typical_errors: ['200·15'], explanation: '0,15·200 = 30.' },

  // ── Günstige Fälle zählen (einstufig) ──────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_faelle', skill_label: 'Günstige Fälle zählen', level: 1, curriculum_seq: 84, input_type: 'NUMERIC', prompt: 'Wie viele gerade Zahlen hat ein Würfel (1–6)?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['2'], explanation: '2, 4, 6 → 3.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_faelle', skill_label: 'Günstige Fälle zählen', level: 2, curriculum_seq: 84, input_type: 'NUMERIC', prompt: 'Karten 1–10. Wie viele sind durch 3 teilbar?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['inkl. 10'], explanation: '3, 6, 9 → 3.' },
  { cluster_name: C, class_level: G, topic: 'Wahrscheinlichkeit', skill_code: 'dz_faelle', skill_label: 'Günstige Fälle zählen', level: 3, curriculum_seq: 84, input_type: 'NUMERIC', prompt: 'Wie viele zweistellige Zahlen lassen sich aus {1,2,3} ohne Ziffernwiederholung bilden?', payload: null, canonical: { value: 6 }, check_type: 'numeric', tolerance: 0, typical_errors: ['9 (mit Wiederholung)'], explanation: '3·2 = 6.' },
]
