// Screening-Item-Entwürfe — Klasse 8, Cluster "Geometrie & Messen".
// Versioniert (PR-Review) + via scripts/seed-screening-items.ts mit
// active=false geseedet; fachliche Freigabe via /admin/screening-items.
// Autogradebar: NUMERIC (canonical {value:Zahl}). Zylinder-Aufgaben
// fragen das Ergebnis als Vielfaches von π (saubere Ganzzahl).

import type { SeedItem } from './zahl-rechnen'

const C = 'Geometrie & Messen'
const G = 8

export const GEOMETRIE_MESSEN_ITEMS: SeedItem[] = [
  // ── Fläche Rechteck ────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_rechteck', skill_label: 'Flächeninhalt Rechteck', level: 1, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Rechteck mit Länge 5 cm und Breite 3 cm. Flächeninhalt in cm²?', payload: null, canonical: { value: 15 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Umfang statt Fläche (16)'], explanation: 'A = 5·3 = 15 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_rechteck', skill_label: 'Flächeninhalt Rechteck', level: 2, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Rechteck 12 m × 7 m. Flächeninhalt in m²?', payload: null, canonical: { value: 84 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Umfang 38'], explanation: 'A = 12·7 = 84 m².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_rechteck', skill_label: 'Flächeninhalt Rechteck', level: 3, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Ein Rechteck hat 48 cm² Fläche und 8 cm Länge. Breite in cm?', payload: null, canonical: { value: 6 }, check_type: 'numeric', tolerance: 0, typical_errors: ['48·8'], explanation: 'b = 48 : 8 = 6 cm.' },

  // ── Fläche Dreieck ─────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_dreieck', skill_label: 'Flächeninhalt Dreieck', level: 1, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Dreieck: Grundseite 6 cm, Höhe 4 cm. Flächeninhalt in cm²?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['ohne :2 (24)'], explanation: 'A = (6·4)/2 = 12 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_dreieck', skill_label: 'Flächeninhalt Dreieck', level: 2, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Dreieck: Grundseite 10 cm, Höhe 7 cm. Flächeninhalt in cm²?', payload: null, canonical: { value: 35 }, check_type: 'numeric', tolerance: 0, typical_errors: ['70'], explanation: 'A = (10·7)/2 = 35 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_dreieck', skill_label: 'Flächeninhalt Dreieck', level: 3, curriculum_seq: 60, input_type: 'NUMERIC', prompt: 'Ein Dreieck hat 24 cm² Fläche und Grundseite 8 cm. Höhe in cm?', payload: null, canonical: { value: 6 }, check_type: 'numeric', tolerance: 0, typical_errors: ['24:8 ohne ·2'], explanation: 'h = 2·24/8 = 6 cm.' },

  // ── Fläche Parallelogramm ──────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_para', skill_label: 'Flächeninhalt Parallelogramm', level: 1, curriculum_seq: 61, input_type: 'NUMERIC', prompt: 'Parallelogramm: Grundseite 5 cm, Höhe 4 cm. Fläche in cm²?', payload: null, canonical: { value: 20 }, check_type: 'numeric', tolerance: 0, typical_errors: [':2 wie Dreieck'], explanation: 'A = g·h = 20 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_para', skill_label: 'Flächeninhalt Parallelogramm', level: 2, curriculum_seq: 61, input_type: 'NUMERIC', prompt: 'Parallelogramm: Grundseite 9 cm, Höhe 6 cm. Fläche in cm²?', payload: null, canonical: { value: 54 }, check_type: 'numeric', tolerance: 0, typical_errors: ['27'], explanation: 'A = 9·6 = 54 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_para', skill_label: 'Flächeninhalt Parallelogramm', level: 3, curriculum_seq: 61, input_type: 'NUMERIC', prompt: 'Parallelogramm: Fläche 60 cm², Höhe 5 cm. Grundseite in cm?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['60·5'], explanation: 'g = 60 : 5 = 12 cm.' },

  // ── Fläche Trapez ──────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_trapez', skill_label: 'Flächeninhalt Trapez', level: 1, curriculum_seq: 62, input_type: 'NUMERIC', prompt: 'Trapez: parallele Seiten a=6 cm, c=4 cm, Höhe 2 cm. Fläche in cm²?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['(a+c)·h ohne :2'], explanation: 'A = ((6+4)/2)·2 = 10 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_trapez', skill_label: 'Flächeninhalt Trapez', level: 2, curriculum_seq: 62, input_type: 'NUMERIC', prompt: 'Trapez: a=8 cm, c=4 cm, Höhe 5 cm. Fläche in cm²?', payload: null, canonical: { value: 30 }, check_type: 'numeric', tolerance: 0, typical_errors: ['60'], explanation: 'A = ((8+4)/2)·5 = 30 cm².' },
  { cluster_name: C, class_level: G, topic: 'Flächeninhalt', skill_code: 'gm_flaeche_trapez', skill_label: 'Flächeninhalt Trapez', level: 3, curriculum_seq: 62, input_type: 'NUMERIC', prompt: 'Trapez: a=10 cm, c=6 cm, Fläche 32 cm². Höhe in cm?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Mittelwert vergessen'], explanation: 'Mittelparallele 8; h = 32/8 = 4 cm.' },

  // ── Volumen Quader ─────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_quader', skill_label: 'Volumen Quader', level: 1, curriculum_seq: 65, input_type: 'NUMERIC', prompt: 'Quader 2 cm × 3 cm × 4 cm. Volumen in cm³?', payload: null, canonical: { value: 24 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Oberfläche'], explanation: 'V = 2·3·4 = 24 cm³.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_quader', skill_label: 'Volumen Quader', level: 2, curriculum_seq: 65, input_type: 'NUMERIC', prompt: 'Quader 5 cm × 4 cm × 10 cm. Volumen in cm³?', payload: null, canonical: { value: 200 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Summe 19'], explanation: 'V = 5·4·10 = 200 cm³.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_quader', skill_label: 'Volumen Quader', level: 3, curriculum_seq: 65, input_type: 'NUMERIC', prompt: 'Quader: Volumen 120 cm³, Grundfläche 24 cm². Höhe in cm?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['120·24'], explanation: 'h = V/G = 120/24 = 5 cm.' },

  // ── Volumen Zylinder (Vielfaches von π) ────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_zylinder', skill_label: 'Volumen Zylinder', level: 1, curriculum_seq: 66, input_type: 'NUMERIC', prompt: 'Zylinder: r=2 cm, h=3 cm. Volumen als Vielfaches von π (nur die Zahl, cm³)?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['r nicht quadriert'], explanation: 'V = π·r²·h = π·4·3 = 12π.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_zylinder', skill_label: 'Volumen Zylinder', level: 2, curriculum_seq: 66, input_type: 'NUMERIC', prompt: 'Zylinder: r=3 cm, h=5 cm. Volumen als Vielfaches von π (nur die Zahl)?', payload: null, canonical: { value: 45 }, check_type: 'numeric', tolerance: 0, typical_errors: ['3·5 statt 9·5'], explanation: 'V = π·9·5 = 45π.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_vol_zylinder', skill_label: 'Volumen Zylinder', level: 3, curriculum_seq: 66, input_type: 'NUMERIC', prompt: 'Zylinder mit Volumen 50π cm³ und r=5 cm. Höhe in cm?', payload: null, canonical: { value: 2 }, check_type: 'numeric', tolerance: 0, typical_errors: ['r nicht quadriert'], explanation: '50π = π·25·h → h = 2 cm.' },

  // ── Oberfläche Quader/Würfel ───────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_ober_quader', skill_label: 'Oberfläche Quader/Würfel', level: 1, curriculum_seq: 67, input_type: 'NUMERIC', prompt: 'Würfel mit Kantenlänge 2 cm. Oberfläche in cm²?', payload: null, canonical: { value: 24 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Volumen 8'], explanation: '6·(2·2) = 24 cm².' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_ober_quader', skill_label: 'Oberfläche Quader/Würfel', level: 2, curriculum_seq: 67, input_type: 'NUMERIC', prompt: 'Quader 3 cm × 4 cm × 5 cm. Oberfläche in cm²?', payload: null, canonical: { value: 94 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur 3 Flächen'], explanation: '2(3·4+3·5+4·5) = 2·47 = 94 cm².' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_ober_quader', skill_label: 'Oberfläche Quader/Würfel', level: 3, curriculum_seq: 67, input_type: 'NUMERIC', prompt: 'Ein Würfel hat 54 cm² Oberfläche. Kantenlänge in cm?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['54/6 ohne Wurzel'], explanation: 'a² = 54/6 = 9 → a = 3 cm.' },

  // ── Mantelfläche Zylinder (Vielfaches von π) ───────────────────────────
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_mantel_zylinder', skill_label: 'Mantelfläche Zylinder', level: 1, curriculum_seq: 68, input_type: 'NUMERIC', prompt: 'Zylinder: r=1 cm, h=5 cm. Mantelfläche als Vielfaches von π (nur die Zahl)?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['ohne Faktor 2'], explanation: 'M = 2π·r·h = 2π·1·5 = 10π.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_mantel_zylinder', skill_label: 'Mantelfläche Zylinder', level: 2, curriculum_seq: 68, input_type: 'NUMERIC', prompt: 'Zylinder: r=2 cm, h=3 cm. Mantelfläche als Vielfaches von π (nur die Zahl)?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['r quadriert'], explanation: 'M = 2π·2·3 = 12π.' },
  { cluster_name: C, class_level: G, topic: 'Körper', skill_code: 'gm_mantel_zylinder', skill_label: 'Mantelfläche Zylinder', level: 3, curriculum_seq: 68, input_type: 'NUMERIC', prompt: 'Zylinder mit Mantelfläche 30π cm² und r=3 cm. Höhe in cm?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['ohne Faktor 2'], explanation: '30π = 2π·3·h → h = 5 cm.' },

  // ── Pythagoras: Hypotenuse ─────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_hyp', skill_label: 'Pythagoras: Hypotenuse', level: 1, curriculum_seq: 70, input_type: 'NUMERIC', prompt: 'Rechtwinkliges Dreieck, Katheten 3 cm und 4 cm. Hypotenuse in cm?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['3+4=7'], explanation: '√(3²+4²) = √25 = 5 cm.' },
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_hyp', skill_label: 'Pythagoras: Hypotenuse', level: 2, curriculum_seq: 70, input_type: 'NUMERIC', prompt: 'Katheten 6 cm und 8 cm. Hypotenuse in cm?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['14'], explanation: '√(36+64) = √100 = 10 cm.' },
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_hyp', skill_label: 'Pythagoras: Hypotenuse', level: 3, curriculum_seq: 70, input_type: 'NUMERIC', prompt: 'Katheten 5 cm und 12 cm. Hypotenuse in cm?', payload: null, canonical: { value: 13 }, check_type: 'numeric', tolerance: 0, typical_errors: ['17'], explanation: '√(25+144) = √169 = 13 cm.' },

  // ── Pythagoras: fehlende Kathete ───────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_kath', skill_label: 'Pythagoras: fehlende Kathete', level: 1, curriculum_seq: 71, input_type: 'NUMERIC', prompt: 'Hypotenuse 5 cm, eine Kathete 3 cm. Andere Kathete in cm?', payload: null, canonical: { value: 4 }, check_type: 'numeric', tolerance: 0, typical_errors: ['addiert statt subtrahiert'], explanation: '√(5²−3²) = √16 = 4 cm.' },
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_kath', skill_label: 'Pythagoras: fehlende Kathete', level: 2, curriculum_seq: 71, input_type: 'NUMERIC', prompt: 'Hypotenuse 13 cm, eine Kathete 5 cm. Andere Kathete in cm?', payload: null, canonical: { value: 12 }, check_type: 'numeric', tolerance: 0, typical_errors: ['√(13²+5²)'], explanation: '√(169−25) = √144 = 12 cm.' },
  { cluster_name: C, class_level: G, topic: 'Pythagoras', skill_code: 'gm_pyth_kath', skill_label: 'Pythagoras: fehlende Kathete', level: 3, curriculum_seq: 71, input_type: 'NUMERIC', prompt: 'Hypotenuse 17 cm, eine Kathete 8 cm. Andere Kathete in cm?', payload: null, canonical: { value: 15 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Quadrate falsch'], explanation: '√(289−64) = √225 = 15 cm.' },
]
