// Screening-Item-Entwürfe — Klasse 8, Cluster "Sachrechnen & Modellieren".
// Versioniert (PR-Review) + via scripts/seed-screening-items.ts mit
// active=false geseedet; Freigabe via /admin/screening-items.
// Autogradebar: NUMERIC (canonical {value}) | MC (canonical {index}).

import type { SeedItem } from './zahl-rechnen'

const C = 'Sachrechnen & Modellieren'
const G = 8

export const SACHRECHNEN_MODELLIEREN_ITEMS: SeedItem[] = [
  // ── Dreisatz direkt ────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_direkt', skill_label: 'Dreisatz (direkt proportional)', level: 1, curriculum_seq: 85, input_type: 'NUMERIC', prompt: '3 Stifte kosten 6 €. Was kosten 5 Stifte (in €)?', payload: null, canonical: { value: 10 }, check_type: 'numeric', tolerance: 0, typical_errors: ['6·5'], explanation: '1 Stift 2 €; 5·2 = 10 €.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_direkt', skill_label: 'Dreisatz (direkt proportional)', level: 2, curriculum_seq: 85, input_type: 'NUMERIC', prompt: '4 m Stoff kosten 12 €. Was kosten 7 m (in €)?', payload: null, canonical: { value: 21 }, check_type: 'numeric', tolerance: 0, typical_errors: ['12·7'], explanation: '3 €/m; 7·3 = 21 €.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_direkt', skill_label: 'Dreisatz (direkt proportional)', level: 3, curriculum_seq: 85, input_type: 'NUMERIC', prompt: 'Für 250 g zahlt man 2 €. Was kosten 600 g (in €)?', payload: null, canonical: { value: 4.8 }, check_type: 'numeric', tolerance: 0, typical_errors: ['ohne Zwischenschritt'], explanation: '2/250·600 = 4,80 €.' },

  // ── Dreisatz indirekt (antiproportional) ───────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_indirekt', skill_label: 'Dreisatz (antiproportional)', level: 1, curriculum_seq: 86, input_type: 'NUMERIC', prompt: '4 Arbeiter brauchen 6 Tage. Wie lange brauchen 8 Arbeiter (Tage)?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['direkt gerechnet (12)'], explanation: '4·6/8 = 3 Tage.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_indirekt', skill_label: 'Dreisatz (antiproportional)', level: 2, curriculum_seq: 86, input_type: 'NUMERIC', prompt: 'Ein Vorrat reicht 10 Tage für 6 Personen. Für wie viele Tage bei 12 Personen?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['20'], explanation: '10·6/12 = 5 Tage.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_dreisatz_indirekt', skill_label: 'Dreisatz (antiproportional)', level: 3, curriculum_seq: 86, input_type: 'NUMERIC', prompt: '3 Pumpen leeren ein Becken in 8 h. Wie lange mit 4 Pumpen (h)?', payload: null, canonical: { value: 6 }, check_type: 'numeric', tolerance: 0, typical_errors: ['8·4/3'], explanation: '3·8/4 = 6 h.' },

  // ── Proportionalität erkennen (MC) ─────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_prop_erkennen', skill_label: 'Proportionalität erkennen', level: 1, curriculum_seq: 87, input_type: 'MC', prompt: 'Mehr Arbeiter → weniger Zeit. Welche Proportionalität liegt vor?', payload: { type: 'mc', options: ['direkt proportional', 'antiproportional', 'keine Proportionalität', 'konstant'], correct_index: 1 }, canonical: { index: 1 }, check_type: 'mc_index', tolerance: null, typical_errors: ['direkt gewählt'], explanation: 'Mehr ↔ weniger = antiproportional.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_prop_erkennen', skill_label: 'Proportionalität erkennen', level: 2, curriculum_seq: 87, input_type: 'MC', prompt: 'Doppelte Menge → doppelter Preis. Welche Proportionalität?', payload: { type: 'mc', options: ['direkt proportional', 'antiproportional', 'keine', 'quadratisch'], correct_index: 0 }, canonical: { index: 0 }, check_type: 'mc_index', tolerance: null, typical_errors: ['antiproportional'], explanation: 'Mehr ↔ mehr (gleicher Faktor) = direkt proportional.' },
  { cluster_name: C, class_level: G, topic: 'Proportionalität', skill_code: 'sm_prop_erkennen', skill_label: 'Proportionalität erkennen', level: 3, curriculum_seq: 87, input_type: 'MC', prompt: 'Konstante Geschwindigkeit: Strecke und Zeit verhalten sich …', payload: { type: 'mc', options: ['direkt proportional', 'antiproportional', 'gar nicht', 'zufällig'], correct_index: 0 }, canonical: { index: 0 }, check_type: 'mc_index', tolerance: null, typical_errors: ['antiproportional'], explanation: 's = v·t mit konstantem v → direkt proportional.' },

  // ── Maßstab ────────────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_massstab', skill_label: 'Maßstab umrechnen', level: 1, curriculum_seq: 88, input_type: 'NUMERIC', prompt: 'Karte im Maßstab 1:100. 3 cm auf der Karte = wie viele cm in Wirklichkeit?', payload: null, canonical: { value: 300 }, check_type: 'numeric', tolerance: 0, typical_errors: ['3/100'], explanation: '3·100 = 300 cm.' },
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_massstab', skill_label: 'Maßstab umrechnen', level: 2, curriculum_seq: 88, input_type: 'NUMERIC', prompt: 'Maßstab 1:50000. 4 cm auf der Karte = wie viele km in Wirklichkeit?', payload: null, canonical: { value: 2 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Einheiten nicht umgerechnet'], explanation: '4·50000 cm = 200000 cm = 2 km.' },
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_massstab', skill_label: 'Maßstab umrechnen', level: 3, curriculum_seq: 88, input_type: 'NUMERIC', prompt: 'Reale Länge 1500 m, Maßstab 1:30000. Länge auf der Karte in cm?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['m statt cm'], explanation: '150000 cm / 30000 = 5 cm.' },

  // ── Einheiten umrechnen ────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_einheiten', skill_label: 'Einheiten umrechnen', level: 1, curriculum_seq: 89, input_type: 'NUMERIC', prompt: 'Wandle 2,5 m in cm um.', payload: null, canonical: { value: 250 }, check_type: 'numeric', tolerance: 0, typical_errors: ['25'], explanation: '2,5·100 = 250 cm.' },
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_einheiten', skill_label: 'Einheiten umrechnen', level: 2, curriculum_seq: 89, input_type: 'NUMERIC', prompt: 'Wandle 3500 g in kg um.', payload: null, canonical: { value: 3.5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['35'], explanation: '3500/1000 = 3,5 kg.' },
  { cluster_name: C, class_level: G, topic: 'Maßstab & Einheiten', skill_code: 'sm_einheiten', skill_label: 'Einheiten umrechnen', level: 3, curriculum_seq: 89, input_type: 'NUMERIC', prompt: 'Wandle 1,2 km in m um.', payload: null, canonical: { value: 1200 }, check_type: 'numeric', tolerance: 0, typical_errors: ['120'], explanation: '1,2·1000 = 1200 m.' },

  // ── Geschwindigkeit ────────────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Bewegung', skill_code: 'sm_geschwindigkeit', skill_label: 'Geschwindigkeit/Strecke/Zeit', level: 1, curriculum_seq: 90, input_type: 'NUMERIC', prompt: '120 km in 2 h. Geschwindigkeit in km/h?', payload: null, canonical: { value: 60 }, check_type: 'numeric', tolerance: 0, typical_errors: ['120·2'], explanation: 'v = 120/2 = 60 km/h.' },
  { cluster_name: C, class_level: G, topic: 'Bewegung', skill_code: 'sm_geschwindigkeit', skill_label: 'Geschwindigkeit/Strecke/Zeit', level: 2, curriculum_seq: 90, input_type: 'NUMERIC', prompt: 'Mit 50 km/h in 3 h. Welche Strecke in km?', payload: null, canonical: { value: 150 }, check_type: 'numeric', tolerance: 0, typical_errors: ['50/3'], explanation: 's = 50·3 = 150 km.' },
  { cluster_name: C, class_level: G, topic: 'Bewegung', skill_code: 'sm_geschwindigkeit', skill_label: 'Geschwindigkeit/Strecke/Zeit', level: 3, curriculum_seq: 90, input_type: 'NUMERIC', prompt: '180 km bei 60 km/h. Benötigte Zeit in h?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['180·60'], explanation: 't = 180/60 = 3 h.' },

  // ── Tarif: Kosten berechnen ────────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_wert', skill_label: 'Tarif-/Kostenmodell auswerten', level: 1, curriculum_seq: 91, input_type: 'NUMERIC', prompt: 'Grundgebühr 5 €, dazu 2 € je Einheit. Kosten bei 4 Einheiten (in €)?', payload: null, canonical: { value: 13 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Grundgebühr vergessen'], explanation: '5 + 4·2 = 13 €.' },
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_wert', skill_label: 'Tarif-/Kostenmodell auswerten', level: 2, curriculum_seq: 91, input_type: 'NUMERIC', prompt: 'Grundgebühr 10 €, 1,50 € je Minute. Kosten bei 20 Minuten (in €)?', payload: null, canonical: { value: 40 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur 30'], explanation: '10 + 20·1,50 = 40 €.' },
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_wert', skill_label: 'Tarif-/Kostenmodell auswerten', level: 3, curriculum_seq: 91, input_type: 'NUMERIC', prompt: 'Tarif: 8 € Grundgebühr + 0,20 € je Minute. Die Rechnung beträgt 20 €. Wie viele Minuten?', payload: null, canonical: { value: 60 }, check_type: 'numeric', tolerance: 0, typical_errors: ['20/0,2'], explanation: '(20−8)/0,2 = 60 Min.' },

  // ── Tarifvergleich (Gleichheitspunkt) ──────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_vergleich', skill_label: 'Tarife vergleichen (Schnittpunkt)', level: 1, curriculum_seq: 92, input_type: 'NUMERIC', prompt: 'Tarif A: 3 € je Stück. Tarif B: 6 € + 1 € je Stück. Ab wie vielen Stück gleich teuer?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['6'], explanation: '3x = 6 + x → 2x = 6 → x = 3.' },
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_vergleich', skill_label: 'Tarife vergleichen (Schnittpunkt)', level: 2, curriculum_seq: 92, input_type: 'NUMERIC', prompt: 'A: 10 € + 2 €/St. B: 4 € + 4 €/St. Bei wie vielen Stück gleich teuer?', payload: null, canonical: { value: 3 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Gleichung falsch aufgestellt'], explanation: '10+2x = 4+4x → 6 = 2x → x = 3.' },
  { cluster_name: C, class_level: G, topic: 'Tarife', skill_code: 'sm_tarif_vergleich', skill_label: 'Tarife vergleichen (Schnittpunkt)', level: 3, curriculum_seq: 92, input_type: 'NUMERIC', prompt: 'A: 20 € + 1 €/St. B: 5 € + 4 €/St. Bei welcher Stückzahl sind beide gleich teuer?', payload: null, canonical: { value: 5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['15'], explanation: '20+x = 5+4x → 15 = 3x → x = 5.' },

  // ── Mehrschrittige Anwendung ───────────────────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_mehrschritt', skill_label: 'Mehrschrittige Anwendungsaufgabe', level: 1, curriculum_seq: 93, input_type: 'NUMERIC', prompt: 'Ein Buch kostet 12 €, es gibt 25 % Rabatt. Endpreis in €?', payload: null, canonical: { value: 9 }, check_type: 'numeric', tolerance: 0, typical_errors: ['nur Rabatt 3'], explanation: '12 − 12·0,25 = 9 €.' },
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_mehrschritt', skill_label: 'Mehrschrittige Anwendungsaufgabe', level: 2, curriculum_seq: 93, input_type: 'NUMERIC', prompt: '3 Hefte je 2 € und 1 Stift für 5 €, darauf 10 % Rabatt aufs Gesamte. Endpreis in €?', payload: null, canonical: { value: 9.9 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Rabatt nur auf Stifte'], explanation: '(6+5)=11; 11·0,9 = 9,90 €.' },
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_mehrschritt', skill_label: 'Mehrschrittige Anwendungsaufgabe', level: 3, curriculum_seq: 93, input_type: 'NUMERIC', prompt: 'Ein Auto fährt 2 h mit 60 km/h, dann 1 h mit 90 km/h. Durchschnittsgeschwindigkeit in km/h?', payload: null, canonical: { value: 70 }, check_type: 'numeric', tolerance: 0, typical_errors: ['(60+90)/2'], explanation: 'Strecke 210 km, Zeit 3 h → 70 km/h.' },

  // ── Anwendungs-Durchschnitt / pro Einheit ──────────────────────────────
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_pro_einheit', skill_label: 'Wert pro Einheit / Durchschnitt', level: 1, curriculum_seq: 94, input_type: 'NUMERIC', prompt: '5 kg Äpfel kosten 10 €. Preis pro kg in €?', payload: null, canonical: { value: 2 }, check_type: 'numeric', tolerance: 0, typical_errors: ['5·10'], explanation: '10/5 = 2 €/kg.' },
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_pro_einheit', skill_label: 'Wert pro Einheit / Durchschnitt', level: 2, curriculum_seq: 94, input_type: 'NUMERIC', prompt: 'Ein Auto verbraucht 30 L auf 400 km. Verbrauch pro 100 km (in L)?', payload: null, canonical: { value: 7.5 }, check_type: 'numeric', tolerance: 0, typical_errors: ['30/400'], explanation: '30/400·100 = 7,5 L.' },
  { cluster_name: C, class_level: G, topic: 'Mehrschritt', skill_code: 'sm_pro_einheit', skill_label: 'Wert pro Einheit / Durchschnitt', level: 3, curriculum_seq: 94, input_type: 'NUMERIC', prompt: '3 Personen teilen 72 € gleichmäßig und legen zusätzlich 6 € Trinkgeld (auch gleich geteilt) drauf. Betrag pro Person in €?', payload: null, canonical: { value: 26 }, check_type: 'numeric', tolerance: 0, typical_errors: ['Trinkgeld vergessen'], explanation: '(72+6)/3 = 26 €.' },
]
