#!/usr/bin/env python3
"""C10 Teil 2A (Fortsetzung): Sichtbefunde fuer die 56 alphabetisch spaeteren Bilder
(r… bis z…), die in der ersten Sichtungsrunde (c10_sicht.S) noch offen waren.
Selbe Struktur wie S: datei -> (sichtbefund, crop_beschreibung, passt_zum_text, alt_text_vorschlag).

Handgesichtet (Bild einzeln heruntergeladen und angesehen). Wiederkehrende Muster:
- Viele EMF-Renders sind KEINE Grafik, sondern reiner Teilaufgaben-Text + Antwortkasten
  oder MC-Optionen als Bild -> sichtbefund "unbrauchbar".
- Einige lösungsrelevante Grafiken sind im Render komplett verloren gegangen
  (Schneekristall, Bordcomputer, Wuerfelzeichnung, 3D-Winkelwuerfel).
"""

S2 = {
 "rauten__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext (Teil II) + Antwortkasten.", "nein", ""),
 "rauten__03_image4.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext (Teil III, Quadrat) + Antwortkasten.", "nein", ""),
 "rauten__04_image5.emf.png": ("unbrauchbar",
   "Keine Grafik: MC-Frage + vier Optionen (0,25x / 0,5x / x / 2x cm²) als Bild — fehlende MC-Optionen des Items, gehoeren strukturiert.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "rubbellose__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und die (leere) Los-Illustration entfernen; Gewinnplan-Tabelle behalten. Die dekorative Los-Abbildung ist im Render leer geblieben, wird zur Loesung aber nicht benoetigt.",
   "ja",
   "Gewinnplan-Tabelle: 3 Fussballbilder = ein echter Fussball, 2 Bilder + 1 Kreis = eine Autofahne, 1 Bild + 2 Kreise = ein Fussballbroetchen, 3 freie Kreise = kein Gewinn."),
 "rubbellose__01_image2.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-II-MC-Frage + Bruch-Optionen (1/3, 3/25, 1/25, 1/300, 1/7500) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "rubbellose__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-II-Text (Deutschlandfahnen) + Antwortkasten.", "nein", ""),
 "schneekristalle__00_image1.emf.png": ("unbrauchbar",
   "Die eigentliche Schneekristall-Abbildung fehlt im Render — sichtbar sind nur Frage + MC-Optionen (3/4/6/12). Ohne den Kristall sind die Symmetrieachsen nicht zaehlbar.",
   "nein", ""),
 "saeulenhoehe__00_image1.emf.png": ("text_eingebrannt",
   "Untere Bildunterschrift-Zeile ('Das Diagramm zeigt drei Saeulen …') abschneiden; Saeulendiagramm auf cm-Raster (Hoehen 8, 4, 6 cm) behalten.",
   "ja",
   "Saeulendiagramm auf Zentimeterraster mit drei Saeulen der Hoehen 8 cm, 4 cm und 6 cm."),
 "saeulenhoehe__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-I-Text + Antwortkasten.", "nein", ""),
 "saeulenhoehe__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-II-Text + Antwortkasten.", "nein", ""),
 "schokoladenpreis__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungssatz oben und 'Es gibt keine Sonderangebote' unten entfernen; Preistabelle (Preis fuer 100 g) behalten.",
   "ja",
   "Tabelle: Preis fuer 100 g je Schokoladensorte — Dunkle 1,50 €, Weisse 1,40 €, Milch 1,10 €, Gefuellte 2,10 €."),
 "schokoladenpreis__01_image2.emf.png": ("text_eingebrannt",
   "Teil-1-Text oben und Antwortzeile unten abschneiden; Schaubild (Preis in € ueber Menge in g, Ursprungsgerade, Wertepaar 200 g→3,00 € markiert) behalten.",
   "ja",
   "Koordinatendiagramm Preis (€) ueber Menge (g), proportionale Ursprungsgerade; Wertepaar 200 g ↔ 3,00 € mit gestrichelten Linien markiert."),
 "schokoladenpreis__02_image3.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-2-MC-Frage + Optionen (Dunkle/Weisse/Milch/Gefuellte Schokolade) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "schrankbreiten__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext unten abschneiden; Abbildung 1 (fuenf Einzelschraenke 30/40/45/50/80 cm) und Abbildung 2 (Kombinationstabelle 70–145 cm) behalten. Zeile '135 =' ist bewusst leer (die zu loesende Aufgabe).",
   "ja",
   "Zwei Abbildungen: fuenf Einzelschraenke der Breiten 30, 40, 45, 50 und 80 cm; Tabelle 'Schrankbreiten' mit Kombinationen von 70 bis 145 cm (Zeile 135 cm frei)."),
 "schrankbreiten__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + leere Antworttabelle (Schrankbreite 30/40/45/50/80 cm × Anzahl) — gehoert strukturiert.",
   "eingeschraenkt: Antworttabelle als Bild", ""),
 "sprechstunde__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben abschneiden; Strichlisten-Tabelle (Zeit × Maedchen/Jungen) behalten.",
   "ja",
   "Strichlisten-Tabelle: Zeitraeume 9–10 / 10–11 / 11–12 Uhr mit Strichlisten fuer Maedchen und Jungen."),
 "sprechstunde__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-I-Text (Maedchen gesamt) + Antwortkasten.", "nein", ""),
 "sprechstunde__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-I-Text (Kinder 10–12 Uhr) + Antwortkasten.", "nein", ""),
 "steilestrasse__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben abschneiden; Abbildung 2 (Steigungsdreieck Ort A/Ort B, 12 m, 100 m, 12 % Gefaelle) behalten. Das Verkehrszeichen (Abbildung 1) ist im Render nicht erschienen, wird aber im Text erklaert.",
   "eingeschraenkt: Verkehrszeichen (Abb. 1) fehlt, Abb. 2 vorhanden",
   "Rechtwinkliges Steigungsdreieck: Ort A oben, Ort B unten, Hoehe 12 m, Horizontalstrecke 100 m, 12 % Gefaelle (nicht massstabsgerecht)."),
 "steilestrasse__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-II-Text (Meerane 13 %) + Antwortkasten.", "nein", ""),
 "steilestrasse__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teil-II-Text (Baldwin Street) + Antwortkasten.", "nein", ""),
 "steilestrasse__03_image4.emf.png": ("text_eingebrannt",
   "Teil-III-Text oben und Antwortzeile/Karoflaeche unten abschneiden; Abbildung 3 (Steigungsdreieck Ort A/Ort B mit Winkel a) behalten.",
   "ja",
   "Rechtwinkliges Steigungsdreieck (Abbildung 3): Ort A oben, Ort B unten, Steigungswinkel a an Ort B (nicht massstabsgerecht)."),
 "streckeimkoordinatenkreuz__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungssatz oben und leeren Antwortkasten unten abschneiden; Koordinatensystem mit eingezeichneter Strecke AD behalten.",
   "ja",
   "Koordinatensystem (x, y von -1 bis 5) mit eingezeichneter Strecke AD: A rechts unten (etwa (3|1)), D links oben."),
 "streckeimkoordinatenkreuz__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + Antwortkasten (Koordinaten B, C).", "nein", ""),
 "streckeimkoordinatenkreuz__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + Antwortkasten (Spiegelpunkte A', D').", "nein", ""),
 "streichholzziehen__00_image1.emf.png": ("unbrauchbar",
   "Keine echte Grafik: Aufgabentext + MC-Optionen (1/5, 1/4, 1/2, 4/5) als Bild. Das referenzierte Foto der Streichhoelzer ist nicht gerendert, wird zur Loesung aber nicht benoetigt.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild; Foto fehlt (nicht loesungsrelevant)", ""),
 "tankinhalt__00_image1.emf.png": ("unbrauchbar",
   "Die Bordcomputer-Anzeige ist nicht gerendert (nur ein Fragment sichtbar); vorhanden sind Einleitungstext und Antwortzeile. Ohne die angezeigten Daten (Verbrauch + Restreichweite) ist das Item nicht loesbar.",
   "nein", ""),
 "thermometeranzeigen__00_image1.emf.png": ("text_eingebrannt",
   "Linken Textblock und Antwortzeile abschneiden; die zwei Thermometer (morgens / mittags, Skala -10 bis 40 °C) behalten.",
   "ja",
   "Zwei Thermometer nebeneinander, Skala -10 bis 40 °C: links 'morgens' (Anzeige etwa -8 °C), rechts 'mittags' (Anzeige etwa +6 °C)."),
 "traktor__00_image1.emf.png": ("unbrauchbar",
   "Keine Grafik: nur Einleitungstext + Liste der vier Massstaebe (1:120, 1:87, 1:50, 1:32).", "nein", ""),
 "traktor__01_image2.emf.png": ("unbrauchbar",
   "Keine Grafik: MC-Frage + Optionen (1:120, 1:87, 1:50, 1:32) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "trapezvariation__00_image1.emf.png": ("text_eingebrannt",
   "Text und Formel A=(a+c)·h/2 links abschneiden; Trapez-Skizze ABCD (Grundseite a unten, Parallelseite c oben, Hoehe h) behalten.",
   "ja",
   "Trapez ABCD mit Grundseite a (AB unten), Parallelseite c (DC oben) und eingezeichneter Hoehe h."),
 "trapezvariation__01_image2.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-II-MC-Frage + vier Optionen (quadriert / verdoppelt / um 2 groesser / nicht beantwortbar) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "trapezvariation__02_image3.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-III-MC (Ja/Nein) + Begruendungs-Karoflaeche.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "unfertigerwuerfel__00_image1.emf.png": ("unbrauchbar",
   "Die Zeichnung des angefangenen Wuerfels fehlt im Render komplett — nur Einleitungstext sichtbar. Ohne die Zeichnung ist nicht erkennbar, welche Wuerfel schon verbaut sind (nicht loesbar).",
   "nein", ""),
 "unfertigerwuerfel__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + Antwortzeile.", "nein", ""),
 "unfertigerwuerfel__02_image3.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-II-MC-Frage + Optionen (19/32/38/51) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "verbindungsstrecken__00_image1.png": ("text_eingebrannt",
   "Dreizeiligen Einleitungstext oben abschneiden; Kreis-Abbildung mit fuenf Punkten A–E und den sechs Verbindungsstrecken zwischen A, B, C, D behalten.",
   "ja",
   "Grauer Kreis mit fuenf Punkten A, B, C, D, E; die Punkte A, B, C, D sind paarweise durch sechs Strecken verbunden, E ist unverbunden."),
 "verbindungsstrecken__01_image2.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-I-Text + Antwortzeile (verweist auf die Zeichnung oben).", "nein", ""),
 "verbindungsstrecken__02_image3.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-III-Text + Antwortzeile.", "nein", ""),
 "wahl__00_image1.png": ("text_eingebrannt",
   "Einleitungssatz oben abschneiden; Saeulendiagramm 'Wahlergebnisse' behalten.",
   "ja",
   "Saeulendiagramm 'Wahlergebnisse' mit vier Parteien: A 33,4 %, B 36,8 %, C 19,8 %, D 6,4 %."),
 "wahl__01_image2.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-I-Text + Antwortzeile (weitere Parteien %).", "nein", ""),
 "wahl__02_image3.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-I-Text + Antwortzeile (Waehler Partei A).", "nein", ""),
 "wahrscheinlicher__00_image1.emf.png": ("unbrauchbar",
   "Keine Grafik: MC-Frage + zwei Optionen (Sechs wuerfeln / Muenze Kopf) + Begruendungs-Karoflaeche.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "werbemarkt__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben abschneiden; Saeulendiagramm Gesamtausgaben Werbung 2010–2015 (in Mrd. €) behalten.",
   "ja",
   "Saeulendiagramm Gesamtausgaben fuer Werbung 2010–2015 in Mrd. €, steigend von etwa 15 auf etwa 21."),
 "werbemarkt__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + Antwortzeile + Karoflaeche.", "nein", ""),
 "wettkampfwaehlen__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben abschneiden; die zwei Abstimmungstabellen (Jungen / Maedchen) behalten.",
   "ja",
   "Zwei Abstimmungstabellen: Jungen (Basketball 19, Fussball 31, Handball 12, Volleyball 8) und Maedchen (Feldhockey 4, Fussball 32, Handball 10, Volleyball 34)."),
 "wettkampfwaehlen__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-Text + Antwortkasten (Jungen / Maedchen).", "nein", ""),
 "winkelgamma__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungssatz oben abschneiden; Dreiecks-Skizze (C, A, B, M mit Winkeln g1/g2 und Basiswinkeln x) und die acht Argumentationskarten K1–K8 behalten.",
   "ja",
   "Dreieck mit Spitze C und Basis AB, Punkt M auf AB (AM, MB, MC gleich lang); Winkel g1, g2 an C, Basiswinkel x; darunter acht Argumentationskarten K1–K8 zum Sortieren."),
 "winkelmessen__00_image1.emf.png": ("text_eingebrannt",
   "Aufgabentext oben und Antwortzeile (a = … °) unten abschneiden; den gezeichneten Winkel a behalten. Wichtig: Fuer die Messung muss der Winkel massstabsgetreu bleiben.",
   "ja",
   "Ein nach rechts geoeffneter Winkel a mit Scheitel links, gebildet aus zwei Schenkeln."),
 "winkelwuerfel__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben abschneiden; die fuenf Wurfergebnis-Formen (Nr. 1–5) behalten. Die 3D-Abbildung des Winkelwuerfels ist im Render nicht erschienen (obere Zellreihe leer).",
   "eingeschraenkt: 3D-Abbildung des Wuerfels fehlt, die fuenf Ergebnis-Formen sind vorhanden",
   "Fuenf moegliche Wurfergebnisse des Winkelwuerfels (1–5): 1 und 2 als stehende Rechtecke, 3 und 5 als L-foermige Flaechen, 4 als keilfoermige Doppelflaeche."),
 "winkelwuerfel__01_image2.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-II-MC (Ergebnis 1 gleichwahrscheinlich mit 2/3/4/5; Ergebnis 5 mit 1/2/3/4) als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "winkelwuerfel__02_image3.emf.png": ("text_eingebrannt",
   "Teil-II-Text oben abschneiden; Haeufigkeitstabelle (Ergebnis 1–5 mit Formsymbolen, Anzahl bei 1000 Wuerfen) behalten. ACHTUNG Render-Fehler: Die Anzahl fuer Ergebnis 3 ist ueberlagert/unleserlich (korrekt 122, da Summe = 1000).",
   "eingeschraenkt: Anzahl fuer Ergebnis 3 im Render ueberlagert (korrekt 122)",
   "Tabelle: Ergebnis 1–5 (mit Formsymbolen), Anzahl bei 1000 Wuerfen 258 / 270 / 122 / 230 / 120, Zeile Wahrscheinlichkeit leer."),
 "zahlenwuerfel__00_image1.emf.png": ("unbrauchbar",
   "Keine Grafik: nur Einleitungstext. Das Foto des W30-Wuerfels ist nicht gerendert, wird zur Loesung aber nicht benoetigt.",
   "nein", ""),
 "zahlenwuerfel__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-I-Text + Antwortkasten.", "nein", ""),
 "zahlenwuerfel__02_image3.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-I-MC + Optionen (1/30, 1/15, 1/2, 'nicht berechenbar') als Bild.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
 "zahlenwuerfel__03_image4.emf.png": ("unbrauchbar",
   "Keine Grafik: Teil-II-MC (Ja/Nein) + Begruendungs-Karoflaeche.",
   "eingeschraenkt: enthaelt MC-Optionen als Bild", ""),
}
