#!/usr/bin/env python3
"""C10 Teil 2A: Sichtbefunde pro heruntergeladenem Bild (handgeprueft, Opus-Sichtung).

Format: datei -> (sichtbefund, crop_beschreibung, passt_zum_text, alt_text_vorschlag)
- sichtbefund: "sauber" | "text_eingebrannt" | "unbrauchbar"
- crop_beschreibung: WAS wegzuschneiden ist (leer wenn nichts)
- passt_zum_text: "ja" | "nein" | "eingeschraenkt: ..."
- alt_text_vorschlag: fuer Items mit leerem alt (alle 379 Assets haben alt="")
"""

S = {
 "ansichteneinestischs__00_image1.png": ("text_eingebrannt",
   "Oberen Aufgabentext-Block (3 Zeilen) abschneiden; Foto (Draufsicht) inkl. der Positions-Labels A-D und 'Abbildung 1' behalten.",
   "ja",
   "Draufsicht eines Tisches mit Teller, Gabel, Glas und Tasse mit Untertasse; am Rand die Kamerapositionen A (unten), B (rechts), C (oben), D (links)."),
 "ansichteneinestischs__01_image2.png": ("text_eingebrannt",
   "Drei Einzelfotos vom schwarzen Hintergrund freistellen (je Ansicht ein Bild); Beschriftungen 'Abbildung 2/3/4' sind im Render verloren (schwarz auf schwarz) und muessen neu gesetzt werden.",
   "eingeschraenkt: Fotos vorhanden, aber Abbildungs-Beschriftungen fehlen (fuer die Loesung 'Abbildung 2: A' noetig)",
   "Drei seitliche Ansichten des gedeckten Tisches aus verschiedenen Kamerapositionen (Abbildung 2 bis 4) untereinander."),
 "bevoelkerungsdichte__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und leeres Antwortfeld unten entfernen; Tabelle (16 Bundeslaender + Bevoelkerungsdichte) behalten.",
   "ja",
   "Tabelle: Bevoelkerungsdichte der 16 deutschen Bundeslaender am 31.12.2009 in Einwohnern pro km², von Baden-Wuerttemberg (301) bis Thueringen (139)."),
 "bevoelkerungsdichte__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortlinie/-kasten. Text steht bereits in parts.",
   "nein",
   ""),
 "bevoelkerungsdichte__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortkasten.",
   "nein",
   ""),
 "bruchundprozentsatz__00_image1.emf.png": ("text_eingebrannt",
   "Aufgabentext oben und leeren Antwortkasten unten entfernen; die auszufuellende Tabelle (Prozentsatz 50/../80, Dezimalbruch 0,5/0,3/..) behalten.",
   "ja",
   "Tabelle mit zwei Zeilen: Prozentsatz (50 %, leer, 80 %) und Dezimalbruch (0,5; 0,3; leer) — zwei Felder sind auszufuellen."),
 "butter__00_image1.emf.png": ("unbrauchbar",
   "Das Butter-Foto fehlt im Render komplett (grosse Leerflaeche zwischen Text oben und Frage unten). Ohne Foto ist das Item nicht loesbar.",
   "nein",
   ""),
 "derriese__00_image1.emf.png": ("unbrauchbar",
   "Die Zeichnung des Kopfteils fehlt im Render (Leerflaeche); enthalten sind nur Aufgabentext, Antwortzeile und Karo-Schreibflaeche.",
   "nein",
   ""),
 "derstern__00_image1.emf.png": ("text_eingebrannt",
   "Frage 'Wie gross ist der Flaecheninhalt...', 'Kreuze an.' und die vier MC-Optionen (7/12/16/20 cm²) unten abschneiden; Gitter (8x8, 1cm-Legende) mit Stern behalten. Hinweis: Die eingebrannten Optionen sind zugleich die fehlenden MC-Optionen des Items.",
   "ja",
   "Vierzackiger Stern in einem 8x8-Zentimetergitter; die Zacken reichen jeweils bis zum Gitterrand, Kaestchenlaenge 1 cm (nicht massstabsgerecht)."),
 "divisionvonzahlen__00_image1.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Einleitungssatz + leerer Kasten.",
   "nein",
   ""),
 "divisionvonzahlen__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik im engeren Sinn: wahr/falsch-Ankreuztabelle mit den vier Teilbarkeits-Aussagen — das sind die fehlenden MC-Optionen des Items; gehoert in strukturierte parts/options statt als Bild.",
   "eingeschraenkt: enthaelt die Aufgabenoptionen, aber als Bild statt strukturiert",
   "Tabelle 'Eine mehrziffrige Zahl ist immer durch 4 teilbar, wenn...' mit vier Aussagen und Ankreuzspalten wahr/falsch."),
 "dreieckszahlen__00_image1.emf.png": ("unbrauchbar",
   "Die Plaettchen-Dreiecksfiguren fehlen im Render: 'Abbildung 1' und die Tabellenzeile 'Veranschaulichung' sind leer. Nur Text + Tabellenwerte D1-D4 sichtbar.",
   "nein",
   ""),
 "dreieckszahlen__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortlinien D5=/D6=.",
   "nein", ""),
 "dreieckszahlen__02_image3.emf.png": ("text_eingebrannt",
   "Keine Grafik: Teilaufgabentext + die fuenf MC-Optionen (6/9/10/11/12) als Ankreuzkaestchen — das sind die Optionen von Teil 2, gehoeren in parts/options.",
   "eingeschraenkt: enthaelt die MC-Optionen von Teil 2 als Bild",
   ""),
 "dreieckszahlen__03_image4.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortlinie Dn=.",
   "nein", ""),
 "dreieckszahlen__04_image5.emf.png": ("unbrauchbar",
   "Die Plaettchen-Darstellung (2x D3 nebeneinander = 3x4-Rechteck) fehlt; nur Textfragmente und Linienreste mit '3' und '4' sichtbar.",
   "nein", ""),
 "dreieckszahlen__05_image6.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortlinie Dn=.",
   "nein", ""),
 "durch1001teilbar__00_image1.emf.png": ("text_eingebrannt",
   "Keine Grafik: kompletter Aufgabentext + Tabelle mit den fuenf Argument-Optionen (geeignet/nicht geeignet) — die fehlenden MC-Optionen des Items, gehoeren in parts/options.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "eckenundkanten__00_image1.emf.png": ("text_eingebrannt",
   "Zeile 'Ergaenze die Tabelle.' oben und leeren Antwortkasten unten entfernen; Tabelle mit Quader- und Pyramiden-Skizze behalten.",
   "ja",
   "Tabelle mit Skizzen eines Quaders und einer Pyramide mit viereckiger Grundflaeche; einzutragen sind Gesamtzahl der Ecken und Kanten (vorgegeben: Quader 12 Kanten, Pyramide 5 Ecken)."),
 "eingefaerbterkoerper__00_image1.emf.png": ("text_eingebrannt",
   "Beide Textzeilen entfernen; die Skizze des Koerpers aus drei Wuerfeln (links oben) behalten.",
   "ja",
   "Schraegbild eines Koerpers aus drei gleich grossen, in einer Reihe versetzt zusammengesetzten Wuerfeln."),
 "eingefaerbterkoerper__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Teilaufgabentext + Antwortzeile '... Seitenflaechen'.",
   "nein", ""),
 "eiscafe__00_image1.png": ("text_eingebrannt",
   "Beide Textzeilen links entfernen; Eistueten-Clipart rechts behalten (rein dekorativ).",
   "ja",
   "Zeichnung einer Eistuete mit drei Kugeln (dekorativ)."),
 "eiscafe__01_image2.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile ... €. Text steht bereits in parts.",
   "nein", ""),
 "eiscafe__02_image3.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Ankreuzoptionen + Karo-Schreibflaeche; Optionen sind im Item bereits strukturiert vorhanden.",
   "nein", ""),
 "figurauszweidreiecken__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungszeile oben links und leeren Antwortkasten unten entfernen; Figur (Rechteck mit Diagonale, Winkelmarkierungen a, b, g, d und rechte-Winkel-Punkte) behalten.",
   "ja",
   "Figur aus zwei Dreiecken: ein flaches Rechteck mit einer Diagonalen; markiert sind Winkel Alpha unten links, Beta an der Diagonalen, Gamma und Delta im oberen rechten Dreieck."),
 "figurauszweidreiecken__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: richtig/falsch-Tabelle mit den fuenf Aussagen/Begruendungen — die fehlenden MC-Optionen des Items, gehoeren in parts/options.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "flaecheninhalt__00_image1.emf.png": ("text_eingebrannt",
   "Frage links oben und Antwortsatz/Kasten unten entfernen; Rechteck mit Bemassung 5 cm x 3 cm behalten.",
   "ja",
   "Rechteck mit den Seitenlaengen 5 cm (unten) und 3 cm (rechts), nicht massstabsgerecht."),
 "freizeitkosten__00_image1.emf.png": ("text_eingebrannt",
   "Enthaelt den KOMPLETTEN im Item fehlenden Aufgabenstamm: Ausgaben-Tabelle Jan-Jun, Dennis-Zitat, Ja/Nein-Optionen, Karoflaeche. Fuer ein Bild-Asset nur die Tabelle behalten; besser Stamm als Text ins Item uebernehmen.",
   "eingeschraenkt: es ist der fehlende Aufgabenstamm selbst",
   "Tabelle: Bettys Ausgaben fuer Freizeitaktivitaeten Januar bis Juni in Euro (31, 31, 20, 28, 30, 40)."),
 "fuehrerschein__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext links entfernen; Tabelle (16 Bundeslaender, Durchfallquoten Theorie/Praxis in %) behalten.",
   "ja",
   "Tabelle: Durchfallquoten der Fuehrerscheinpruefungen 2009 je Bundesland, getrennt nach Theorie und Praxis in Prozent (Quelle: Kraftfahrt-Bundesamt 2009)."),
 "fuehrerschein__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile ... %.",
   "nein", ""),
 "fuehrerschein__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Ankreuzoptionen + Karoflaeche; Optionen sind im Item strukturiert vorhanden.",
   "nein", ""),
 "geradenimkoordinatensystem__00_image1.emf.png": ("text_eingebrannt",
   "Titelzeile 'Die Abbildung zeigt die Gerade...' (ueberlappt das Gitter) entfernen; Koordinatensystem mit Gerade behalten. Achtung: Achsenbeschriftungen (0, 1, 5, x) sind im Render leicht verrutscht.",
   "ja",
   "Koordinatensystem mit Kaestchengitter und der Geraden y = 1/2 x - 2; die Gerade steigt nach rechts und schneidet die x-Achse bei x = 4."),
 "geradenimkoordinatensystem__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: Frage + die vier MC-Optionen (x=-2, x=0, x=4, x=5) — die fehlenden Optionen des Items, gehoeren in parts/options.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "geschwindigkeit__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben entfernen; Bussgeld-Tabelle (Geschwindigkeitsueberschreitung / bisher / jetzt) behalten.",
   "ja",
   "Tabelle der neuen Bussgelder fuer Geschwindigkeitsueberschreitungen innerorts: von 'um 21 bis 25 km/h' (80 Euro) bis 'ueber 70 km/h' (760 Euro), jeweils mit altem und neuem Betrag."),
 "geschwindigkeit__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: Teilaufgabentext + vier MC-Optionen (60/100/175/280 Euro) — die fehlenden Optionen des Items.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "gewerbezone__00_image1.emf.png": ("unbrauchbar",
   "Das beworbene Plakat (mit den Flaechenangaben der Gewerbezone) fehlt im Render komplett — nur zwei Textzeilen. Ohne Plakat ist das Item nicht loesbar.",
   "nein", ""),
 "gewerbezone__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Frage + Antwortsatz 'In hoechstens ___ Grundstuecke.'",
   "nein", ""),
 "gewitter__00_image1.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur der Stimulustext (steht bereits im Item).",
   "nein", ""),
 "gewitter__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortsatz.",
   "nein", ""),
 "gewitter__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + MC-Optionen (im Item bereits strukturiert vorhanden).",
   "nein", ""),
 "gueterverkehr__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben entfernen; Diagramm (Kosten je Tonne vs. Transportweg, Graphen LKW/Bahn/Binnenschiff) behalten.",
   "ja",
   "Liniendiagramm: Kosten je Tonne in Euro in Abhaengigkeit von der Laenge des Transportweges (0-500 km) fuer LKW (steilste Gerade ab 100), Bahn und Binnenschiff (flachste Gerade, hoeherer Startwert)."),
 "gueterverkehr__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile ___ €.",
   "nein", ""),
 "gueterverkehr__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + MC-Optionen (LKW/Bahn/Binnenschiff, im Item strukturiert vorhanden).",
   "nein", ""),
 "hauptstaedte__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und Copyright-Zeile unten entfernen; Karte mit Staedtenamen und Massstabskasten (1cm=360km) behalten. Achtung: Laenderumrisse sind im Render stark degradiert (Polygonverlust), Staedtepositionen und Massstab aber vorhanden.",
   "eingeschraenkt: Positionen/Massstab ok, Umrisse fehlerhaft gerendert",
   "Vereinfachte Europakarte mit den Hauptstaedten (Reykjavik bis Nikosia); links unten Massstabsangabe 1 cm entspricht 360 km."),
 "hauptstaedte__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortkasten ... km.",
   "nein", ""),
 "hauptstaedte__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + MC-Optionen (im Item strukturiert vorhanden).",
   "nein", ""),
 "haushaltsabfaelle__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und leeren Antwortkasten unten entfernen; Saeulendiagramm + Bundesland-Nummernliste behalten. Achtung: y-Achsen-Titel ist im Render zeichenweise verwuerfelt.",
   "ja",
   "Saeulendiagramm: Haushaltsabfaelle pro Einwohner in kg im Jahr 2009 fuer die 16 Bundeslaender (nummeriert 1-16, Zuordnung per Tabelle rechts); Werte zwischen ca. 320 kg (Sachsen) und ca. 515 kg (Rheinland-Pfalz)."),
 "haushaltsabfaelle__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Ergaenzungssatz.",
   "nein", ""),
 "haushaltsabfaelle__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Antwortzeile ... kg.",
   "nein", ""),
 "holzwuerfel__00_image1.emf.png": ("text_eingebrannt",
   "Textzeilen oben entfernen; Beispiel-Skizze des Dreierturms (drei Wuerfel uebereinander, beschriftet gelb/blau/rot) behalten; Copyright-Zeile 'Grafik: (c) IQB' beim Crop mitfuehren oder als Attribution ausspielen.",
   "ja",
   "Skizze eines Turms aus drei uebereinander gestapelten Wuerfeln, von oben nach unten beschriftet mit gelb, blau und rot."),
 "holzwuerfel__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Frage + Antwortzeile 'Anzahl der Moeglichkeiten: ...'.",
   "nein", ""),
 "honigbiene__00_image1.emf.png": ("unbrauchbar",
   "Das Bienenfoto fehlt im Render komplett; enthalten sind nur Frage und die vier MC-Optionen (1,5 mm / 1,5 cm / 1,5 dm / 1,5 m) — zugleich die fehlenden Optionen des Items. Ohne Foto nicht loesbar (Antwort 1,5 cm aber durch Alltagswissen erschliessbar).",
   "nein", ""),
 "imkreislaufen__00_image1.emf.png": ("unbrauchbar",
   "Von den vier Antwort-Graphen enthaelt nur der erste eine Kurve (Dreiecksverlauf); die Kurven der Graphen 2-4 fehlen im Render (leere Achsenkreuze). Als MC-Grundlage unbrauchbar.",
   "nein", ""),
 "internetauktion__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben entfernen; Tabelle (Auktionsnummer 1-9 / Endpreis) behalten.",
   "ja",
   "Tabelle: Endpreise von neun Notebook-Auktionen, Auktionsnummer 1 bis 9 mit Preisen zwischen 355 und 449 Euro."),
 "internetauktion__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Frage + Antwortzeile.",
   "nein", ""),
 "internetauktion__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Frage + Antwortzeile.",
   "nein", ""),
 "koerperfuellen__00_image1.emf.png": ("text_eingebrannt",
   "Textzeilen oben und Copyright unten entfernen; Grafik (Quader mit teilweise eingefuellten 1-cm-Wuerfeln + Einzelwuerfel mit Bemassung 1cm) behalten.",
   "ja",
   "Schraegbild eines Quaders, dessen Boden- und Seitenreihen teilweise mit kleinen Wuerfeln gefuellt sind; daneben ein einzelner Wuerfel mit Kantenlaenge 1 cm."),
 "koerperfuellen__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: Frage + fuenf MC-Optionen (14/16/74/90/126 cm³) — die fehlenden Optionen des Items.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "kopfundkoerper__00_image1.emf.png": ("text_eingebrannt",
   "Textblock links entfernen; Skizze rechts (Strichfigur mit Markierung Kopf=1, Koerper=4) behalten.",
   "ja",
   "Schematische Strichfigur eines Babys; die Kopflaenge ist mit 1, die restliche Koerperlaenge mit 4 markiert (Verhaeltnis 1:4)."),
 "kopfundkoerper__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile.",
   "nein", ""),
 "kopfundkoerper__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Antwortzeile.",
   "nein", ""),
 "kreisfiguren__00_image1.png": ("text_eingebrannt",
   "Einleitungszeile oben abschneiden; Kaestchengitter mit den grauen Figuren A-D behalten (PNG, gute Qualitaet).",
   "ja",
   "Vier grau gefaerbte Figuren in einem Kaestchengitter, begrenzt durch Kreislinien und Strecken: Figur A (nach innen gewoelbtes Quadrat/Stern), Figur B (Quadrat mit ausgebuchteten Halbkreisen), Figur C (Kreis), Figur D (halbkreisfoermige Figur)."),
 "kreisfiguren__01_image2.png": ("unbrauchbar",
   "Kein Bildinhalt: Frage + Ergaenzungssatz 'Figur _ und Figur _ ...'.",
   "nein", ""),
 "lagederwuerfel__00_image1.emf.png": ("unbrauchbar",
   "Die Augenzahlen auf den vier Spielwuerfeln fehlen im Render (nur leere Wuerfel-Schraegbilder). Ohne die abgebildeten Augenzahlen ist das Item nicht loesbar.",
   "nein", ""),
 "lagederwuerfel__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Frage, Antwortsatz und Karo-Schreibflaeche; die grau markierte Seitenflaeche ist ohnehin nur in der (verlorenen) Abbildung erkennbar.",
   "nein", ""),
 "luftballons__00_image1.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: nur Stimulustext (steht bereits im Item).",
   "nein", ""),
 "luftballons__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: Frage + vier MC-Optionen als Brueche (1/100, 4/10, 1/2, 6/10) — die fehlenden Optionen des Items.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "massstabsleiste__00_image1.emf.png": ("text_eingebrannt",
   "Frage, 'Kreuze an.' und die vier MC-Optionen (1:500 bis 1:500000) unten entfernen; Massstabsleiste (0-2000 m, 1-cm-Referenzpfeil) oben behalten. Die eingebrannten Optionen sind zugleich die fehlenden MC-Optionen des Items.",
   "ja",
   "Massstabsleiste einer Atlaskarte: Balken von 0 bis 2000 m in 500-m-Schritten; darueber ein Doppelpfeil, der 1 cm auf der Karte markiert."),
 "muckibude__00_image1.png": ("text_eingebrannt",
   "Einleitungszeilen oben abschneiden; Saeulendiagramm behalten (PNG, gute Qualitaet).",
   "ja",
   "Saeulendiagramm: Mitgliederzahlen des Fitnessvereins Muckibude 2012 bis 2016; Werte 200, 400, 800, 1200 und 1800 Mitglieder."),
 "muckibude__01_image2.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Frage + Antwortzeile.",
   "nein", ""),
 "muckibude__02_image3.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Frage + Antwortzeile.",
   "nein", ""),
 "naschkatze__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben, degradiertes Cafe-Schild rechts und Copyright-Zeilen entfernen; Umsatz-Saeulendiagramm links behalten. Achtung: y-Achsen-Titel im Render zeichenweise verwuerfelt.",
   "ja",
   "Saeulendiagramm: Umsatz des Cafes Naschkatze in Euro je Quartal des ersten Geschaeftsjahres — 8000, 10000, 14000 und 16000 Euro."),
 "naschkatze__01_image2.emf.png": ("text_eingebrannt",
   "Keine Grafik: Frage + vier MC-Optionen (1.-4. Quartal) — die fehlenden Optionen des Items.",
   "eingeschraenkt: enthaelt die MC-Optionen als Bild",
   ""),
 "niederschlag__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und Datenquellen-/Antwortkasten unten entfernen; Klimadiagramm behalten. Achtung: beide Achsentitel im Render zeichenweise verwuerfelt.",
   "ja",
   "Klimadiagramm Halle an der Saale 2012: Saeulen fuer monatlichen Niederschlag in mm (Maximum Juni ca. 61 mm), Linie/Punkte fuer die durchschnittliche Monatstemperatur in Grad Celsius (Minimum Januar, Maximum Juli ca. 18 Grad)."),
 "niederschlag__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Frage + Antwortkasten.",
   "nein", ""),
 "niederschlag__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Frage + MC-Optionen (im Item strukturiert vorhanden).",
   "nein", ""),
 "niederschlag__03_image4.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-3-Frage + Antwortkasten.",
   "nein", ""),
 "niederschlag__04_image5.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-4-Frage + Ja/Nein + Karoflaeche (im Item strukturiert vorhanden).",
   "nein", ""),
 "ohrhaenger__00_image1.emf.png": ("text_eingebrannt",
   "Textblock links und Antwortkasten unten entfernen; Ohrhaenger-Skizze rechts (senkrechter Draht mit 3-cm-Markierung + gleichseitiges Dreieck, 'nicht massstabsgerecht') behalten.",
   "ja",
   "Skizze eines Ohrhaengers: ein 3 cm langer gerader Drahtabschnitt, an dessen unterem Ende ein gleichseitiges Dreieck haengt (nicht massstabsgerecht)."),
 "ohrhaenger__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile + Karoflaeche.",
   "nein", ""),
 "ohrhaenger__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Antwortzeile + Karoflaeche.",
   "nein", ""),
 "parfum__00_image1.emf.png": ("unbrauchbar",
   "Die Fotos (Abbildung 1: Parfumflasche, Abbildung 2: Zerstaeuber-Troepfchen) fehlen im Render — nur Stimulustext und die leeren Beschriftungen 'Abbildung 1 / Abbildung 2'. Bilder sind rein illustrativ, Item bleibt ohne sie loesbar.",
   "nein", ""),
 "parfum__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Text + Antwortzeile.",
   "nein", ""),
 "parfum__02_image3.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-2-Text + Antwortzeile + Karoflaeche.",
   "nein", ""),
 "passendeschuhe__00_image1.emf.png": ("text_eingebrannt",
   "Textblock links entfernen; Balkendiagramm 'Die Schuhe sind...' (zu klein/passend/zu gross, Frauen vs. Maenner, 0-80) behalten.",
   "ja",
   "Balkendiagramm einer Befragung: Anteile von je 100 Frauen und Maennern, deren Schuhe zu klein (20/10), passend (20/15) oder zu gross (60/75) sind."),
 "passendeschuhe__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Frage + Ja/Nein + Karoflaeche (Optionen im Item strukturiert vorhanden).",
   "nein", ""),
 "passendeschuhe__02_image3.emf.png": ("unbrauchbar",
   "Die Kreisdiagramm-Vorlage (Abbildung 2) ist im Render zerstoert: der Kreis fehlt, nur lose Sektorlinien und Beschriftungen. Teil-2-Optionen sind im Item strukturiert vorhanden.",
   "nein", ""),
 "prozentanteilschaetzen__00_image1.emf.png": ("unbrauchbar",
   "Die Kreisgrafik mit grau gefaerbtem Anteil fehlt im Render komplett; enthalten sind nur Frage + MC-Optionen (20/30/50/70/80 %) — zugleich die fehlenden Optionen des Items. Ohne Grafik nicht loesbar.",
   "nein", ""),
 "pyramidenbau__00_image1.emf.png": ("unbrauchbar",
   "Die Abbildungen 1 (Pyramide) und 2 (Netz) fehlen im Render; nur Stimulustext. Ohne die Abbildungen ist das Item kaum loesbar (Anzahl Staebe/Kugeln muss aus den Abbildungen gezaehlt werden — mit Fachwissen Tetraeder aber rekonstruierbar).",
   "nein", ""),
 "pyramidenbau__01_image2.emf.png": ("unbrauchbar",
   "Komplett leeres (weisses) Bild — Renderfehler.",
   "nein", ""),
 "pyramidenbau__02_image3.emf.png": ("unbrauchbar",
   "Nur die Beschriftungen 'Foto: (c) IQB' und 'Abbildung 1 / Abbildung 2' — die Fotos selbst fehlen im Render.",
   "nein", ""),
 "pyramidenbau__03_image4.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Frage + Antwortzeilen '... Staebe ... Kugeln'.",
   "nein", ""),
 "quadernetz__00_image1.emf.png": ("text_eingebrannt",
   "Einleitungstext oben und ja/nein-Ankreuzspalten entfernen; die vier Netz-Zeichnungen behalten. Die vier Netze sind zugleich die fehlenden Optionen der MC-Matrix.",
   "ja",
   "Tabelle mit vier Flaechennetzen, jeweils mit ja/nein-Ankreuzfeldern: zu pruefen ist, ob es sich um das Netz eines Quaders handelt."),
 "quadernetz2__00_image1.emf.png": ("text_eingebrannt",
   "Frage oben und Ankreuzkaestchen links entfernen; die vier Netz-Zeichnungen behalten. Die vier Netze sind zugleich die fehlenden MC-Optionen.",
   "ja",
   "Vier Anordnungen von Rechtecken (Netz-Kandidaten); nur eine davon ist das vollstaendige Netz eines Quaders."),
 "quadratimgitter__00_image1.emf.png": ("text_eingebrannt",
   "Textzeilen oben sowie Frage + Antwortzeile unten entfernen; Gitter (8x8, 1-cm-Legende) mit schraeg einbeschriebenem Quadrat behalten.",
   "ja",
   "Ein um 45 Grad gedrehtes Quadrat, dessen Ecken auf Gitterpunkten eines 8x8-Zentimeterrasters liegen (Diagonalen 8 cm); 1 Kaestchen entspricht 1 cm²."),
 "raeumungsverkauf__00_image1.emf.png": ("text_eingebrannt",
   "Textblock links entfernen; Schild-Grafik 'RAEUMUNGSVERKAUF wegen Geschaeftsaufgabe' mit verstreuten Prozentangaben (Abbildung 1) behalten (leicht degradiert, aber lesbar).",
   "ja",
   "Schaufenster-Schild mit der Aufschrift Raeumungsverkauf wegen Geschaeftsaufgabe und verstreuten Rabattangaben von 10 % bis 50 %."),
 "raeumungsverkauf__01_image2.emf.png": ("text_eingebrannt",
   "Frage, Ja/Nein-Optionen und Karoflaeche entfernen; Preisschild-Grafik (64 € durchgestrichen, Anhaenger '-25 %', Abbildung 2) behalten. Schildformen im Render leicht zerfallen, Angaben lesbar.",
   "ja",
   "Preisschild einer Jeans: urspruenglicher Preis 64 Euro (durchgestrichen) und ein Anhaenger mit -25 %."),
 "raeumungsverkauf__02_image3.emf.png": ("text_eingebrannt",
   "Frage, Ja/Nein und Karoflaeche entfernen; Preisangabe (Abbildung 3: 'vorher 120 € / jetzt 69 €') behalten. Der Schild-Rahmen ist im Render verloren, die Zahlen sind lesbar.",
   "eingeschraenkt: Schildgrafik verloren, Kerninfo (120/69 €) als Text vorhanden",
   "Preisschild einer Jacke: vorher 120 Euro, jetzt 69 Euro."),
 "rauminhaltvonprismen__00_image1.emf.png": ("text_eingebrannt",
   "Nur die beiden Koerper-Skizzen oben behalten; Stimulustext und die vier Aussagen-Optionen unten entfernen (sie sind zugleich die fehlenden MC-Optionen und gehoeren in parts/options). Achtung: Hoehenbeschriftungen (16 cm) im Render zeichenweise verwuerfelt.",
   "ja",
   "Skizzen zweier Prismen gleicher Hoehe 16 cm: Koerper A mit quadratischer Grundflaeche (Kantenlaenge a = 10 cm), Koerper B mit sechseckiger Grundflaeche (G = 100 cm²)."),
 "rauten__00_image1.emf.png": ("text_eingebrannt",
   "Stimulustext oben entfernen; Koordinatensystem (0-10, 1-cm-Gitter) mit der Geraden g (y=x) und den Rauten A4B4C4D4 und A7B7C7D7 behalten.",
   "ja",
   "Koordinatensystem mit der Geraden y = x und zwei Rauten: Eckpunkte D4(4|4) bzw. D7(7|7) auf der Geraden, B4 und B7 auf der x-Achse, Diagonalen AC jeweils 2 cm."),
 "rauten__01_image2.emf.png": ("unbrauchbar",
   "Kein Bildinhalt: Teil-1-Frage + Antwortzeile ... cm².",
   "nein", ""),
}
