#!/usr/bin/env python3
"""C10 Teil 1: Stoffanker-Urteile pro Item (handklassifiziert, Referenz NRW-Progression).

Format: Titel -> (grade, konfidenz, kandidaten, textindiz, begruendung, duration_sec)
- grade: 5-9 oder None (bei nicht_bestimmbar)
- konfidenz: "sicher" | "unsicher" | "nicht_bestimmbar"
- kandidaten: "7/8" bei unsicher, sonst ""
- textindiz: Kurzzitat aus question/parts/EMF-Text
- duration_sec: est_duration_sec-VORSCHLAG (kein DB-Write)

Konventionen (im Bericht dokumentiert):
- Grosse Zahlen/Stellenwert/Runden/Ueberschlag -> 5; Geld/einfache Groessen mit nat. Zahlen -> 5
- Koordinatensystem 1. Quadrant, Rechteck-Umfang/Flaeche, Quader/Wuerfel, Netze, Symmetrie, Daten ablesen -> 5
- Brueche/Dezimalzahlen, Massstab, Winkel messen, Volumen Quader, Laplace einstufig, Mittelwert, Kombinatorik (5/6) -> 6
- Prozent/Zinsen, Dreisatz/Proportionalitaet, negative Zahlen, Winkelsaetze, Dreiecks-/Trapezflaechen (7/8) -> 7
- Gleichungen (formale Variable), lineare Funktionen, mehrstufige Zufallsversuche, Prismen, Kreis -> 8
- Kaestchen-/Platzhalteraufgaben ohne formale Variable -> 5
"""

T = {
 "20 Prozent": (7, "sicher", "", "Berechne 20% von 80m.", "Prozentwert berechnen — Prozentrechnung", 45),
 "700 Milliarden": (5, "sicher", "", "Schreibe diese Zahl in Ziffern.", "Grosse Zahlen im Stellenwertsystem schreiben", 60),
 "Abstand auf dem Wasser": (7, "unsicher", "6/7", "faehrt mit gleichbleibender Geschwindigkeit", "Weg-Zeit/proportionale Zuordnung, Aufgabenteile fehlen aber", 90),
 "Adventskalender": (6, "unsicher", "6/7", "wie wahrscheinlich es ist, dass ihr Name an diesem Tag gezogen wird", "Laplace einstufig, aber mit veraenderlicher Grundmenge (anspruchsvoll)", 150),
 "Ampelkarte": (6, "unsicher", "6/7", "wann ein Anteil als gering, mittel oder hoch einzustufen ist", "Dezimalgroessen vergleichen (6); Teil 2 verlangt Halbieren/Umbasieren Richtung Proportionalitaet (7)", 240),
 "Andere Länder - andere Noten": (7, "unsicher", "7/8", "Note = (Erreichte Punktzahl / Maximalpunktzahl) · 5 + 1", "Formel/Term auswerten; Aufgabenteile fehlen", 120),
 "Ansichten eines Tischs": (5, "sicher", "", "von verschiedenen seitlichen Kamerapositionen A bis D aus fotografiert", "Raeumliches Vorstellen/Ansichten zuordnen", 90),
 "Anteile in geometrischen Objekten": (6, "unsicher", "6/7", "Trage jeweils einen passenden Bruch und einen passenden Prozentsatz ein", "Bruch-Anteile (6), aber Prozentsatz verlangt (7)", 120),
 "Anzahl von Nullen": (5, "sicher", "", "Wie viele Nullen hat eine Milliarde (EMF-Text)", "Grosse Zahlen/Stellenwertsystem", 90),
 "Apfelsaftschorle": (6, "sicher", "", "vier fuenftel Liter Apfelsaft mit einem halben Liter Mineralwasser", "Bruchrechnung/Addition von Bruechen mit Groessen", 90),
 "Aufgabenreihen": (5, "unsicher", "5/7", "1 + 3 + 5 = 9", "Zahlenmuster (5); Verallgemeinerung Richtung Terme (7) moeglich, Teilaufgaben fehlen", 120),
 "Aussagen zur proportionalen Zuordnung": (7, "sicher", "", "Graphen einer proportionalen Zuordnung", "Proportionale Zuordnung", 120),
 "Aussagen über Dreiecke": (7, "sicher", "", "b=45° und g=2·a. Wie gross ist a? (EMF-Text)", "Innenwinkelsumme + Term aufstellen — Winkelsaetze Kl. 7", 150),
 "Autokauf": (7, "sicher", "", "Preisermaessigung von 12 % ... 19 % Mehrwertsteuer", "Verkettete Prozentrechnung", 120),
 "Außenthermometer": (7, "sicher", "", "Ein Aussenthermometer zeigt -4°C (EMF-Text)", "Negative Zahlen/Temperaturdifferenzen", 120),
 "Bahncard": (7, "sicher", "", "erhaelt er eine Ermaessigung von 25 % auf den Normalpreis", "Prozentrechnung + Lohnt-sich-Vergleich", 180),
 "Berechne x": (8, "sicher", "", "Gegeben ist die Gleichung 8x = 72.", "Lineare Gleichung mit formaler Variable", 45),
 "Berechnungen am Rechteck": (5, "sicher", "", "Gib den Flaecheninhalt des abgebildeten Rechtecks an (EMF: 3 cm / 5 cm)", "Umfang/Flaeche Rechteck", 120),
 "Bernd und das Brot": (5, "sicher", "", "Verwende 500 g, 5 kg sowie 55,5 kg jeweils einmal.", "Groessenvorstellung Gewicht", 90),
 "Besondere Vierecke": (5, "sicher", "", "Vervollstaendige diese zu einem Rechteck. Zeichne mit Geodreieck", "Rechteck zeichnen mit Geodreieck", 120),
 "Bestimme x": (8, "sicher", "", "Es gilt x − 5 = 15.", "Lineare Gleichung mit formaler Variable", 45),
 "Bevölkerungsdichte": (6, "unsicher", "6/7", "Gib die Differenz zwischen dem groessten und dem kleinsten Wert an (Spannweite)", "Tabelle auswerten + Kenngroesse Spannweite (6/7-Grenze)", 150),
 "Bewege C": (7, "unsicher", "6/7", "dazu die Mittelsenkrechte m und ein Punkt C auf m", "Mittelsenkrechte/gleichschenklige Dreiecke; Aufgabenteile fehlen", 120),
 "Bistroumfrage": (None, "nicht_bestimmbar", "", "plant eine statistische Untersuchung zum Kaufverhalten", "Nur Stimulus vorhanden, Teilaufgaben fehlen — Anker zwischen Daten 5/6 und Auswertung 7 nicht entscheidbar", 120),
 "Bonbons": (6, "sicher", "", "Mit welcher Wahrscheinlichkeit ist es rot?", "Laplace-Wahrscheinlichkeit einstufig", 60),
 "Brettspiel": (None, "nicht_bestimmbar", "", "darf immer um genau so viele Felder weitergeschoben werden", "Eigentliche Frage fehlt (nur Spielbeschreibung)", 120),
 "Briefmarkenschachteln": (5, "unsicher", "5/6", "Hier sind Netze fuer weitere Schachteln ... Vervollstaendige die Beschriftung.", "Netze von Quadern/Schachteln", 150),
 "Bruch und Prozentsatz": (6, "unsicher", "6/7", "stehen Prozentsaetze und zugehoerige Dezimalbrueche", "Umwandlung Dezimalbruch/Prozentsatz an der 6/7-Grenze", 90),
 "Brötchen": (5, "sicher", "", "3 Broetchen fuer insgesamt 95 Cent gekauft", "Sachrechnen mit Geld, natuerliche Zahlen", 150),
 "Butter": (5, "unsicher", "5/6", "wie viel Butter sie ungefaehr von diesem 250-g-Stueck abgeteilt hat", "Groessen schaetzen am Bild; evtl. Anteilsvorstellung (6)", 60),
 "Chancen": (6, "sicher", "", "gewinnen beim Drehen der Gluecksraeder, wenn der Zeiger auf ein graues Feld zeigt", "Wahrscheinlichkeit einstufig (Gluecksrad)", 90),
 "Colakästen": (5, "sicher", "", "Ein Kasten mit 12 Flaschen kostet 6,66 €. Hinzu kommen 3,30 € Pfand.", "Sachrechnen mit Geld", 180),
 "Computerspielsucht": (7, "sicher", "", "jeder neunte Jugendliche ... Wie viel Prozent der Jugendlichen sind das?", "Anteil in Prozentsatz umrechnen", 60),
 "Croissant": (5, "sicher", "", "bezahlt beides mit einem 50€-Schein und bekommt 4,95€ zurueck", "Sachrechnen mit Geld", 60),
 "Damenuhr": (6, "unsicher", "5/6", "mit vier verschiedenen Wechselringen und vier verschiedenen Wechselarmbaendern kombiniert", "Kombinatorik/Zaehlprinzip (5/6)", 90),
 "Darstellung in Diagrammen": (5, "sicher", "", "In welchem Jahr sind 65 Millionen Flaschen verkauft worden?", "Diagramm ablesen", 60),
 "Das ist gerundet": (6, "sicher", "", "Runde die Zahl 5,143 auf eine Stelle nach dem Komma.", "Dezimalzahlen runden", 45),
 "Deckungsgleiche Parallelogramme": (6, "unsicher", "6/7", "dass zwei zueinander deckungsgleiche Parallelogramme entstehen", "Vierecke/Deckungsgleichheit (6) vs. Kongruenz (7)", 120),
 "Der Riese": (7, "unsicher", "6/7", "Wie gross waere ein Riese ungefaehr, zu dem dieser Teil des Kopfes gehoert?", "Verhaeltnis-/Massstabsschaetzung, Modellieren", 180),
 "Der Stern": (7, "unsicher", "7/8", "Wie gross ist der Flaecheninhalt des abgebildeten Sterns?", "Flaecheninhalt zusammengesetzter Figuren (Dreiecksflaechen, 7/8-Band)", 120),
 "Division von Zahlen": (5, "unsicher", "5/6", "wenn bei der Division kein Rest bleibt", "Teilbarkeit (5/6)", 120),
 "Drehkörper": (5, "sicher", "", "Ein Koerper, der aus fuenf gleich grossen Wuerfeln besteht, wird gedreht.", "Raumvorstellung/Ansichten", 60),
 "Dreieck im Quadrat": (7, "unsicher", "7/8", "Mit welchem Rechenschritt kann man die Anzahl ... berechnen?", "Muster/rekursive Bildungsvorschrift + Anteilsargument", 240),
 "Dreieck im Rechteck": (None, "nicht_bestimmbar", "", "", "Keine Aufgabendaten (nur GeoGebra-Datei, kein Stamm extrahierbar)", None),
 "Dreiecke ergänzen": (6, "unsicher", "5/6", "Ergaenze das gegebene Dreieck zu zwei verschiedenen Parallelogrammen.", "Vierecke/Parallelogramm-Eigenschaften", 120),
 "Dreieckszahlen": (8, "unsicher", "7/8", "Gib eine Formel an, mit der man eine beliebige Dreieckszahl Dn berechnen kann", "Zahlenfolgen und Termaufstellung (Verallgemeinerung)", 300),
 "Druckmaschinen": (7, "sicher", "", "kann in vier Stunden 60000 Boegen Papier bedrucken", "Proportionaler/antiproportionaler Dreisatz", 150),
 "Durch 1001 teilbar": (5, "unsicher", "5/8", "eine sechsstellige Zahl, die immer durch 1001 teilbar ist", "Stoff: Teilbarkeit/Stellenwert (5/6); Argumentniveau algebraisch (8)", 150),
 "Ecken an Pyramiden": (5, "sicher", "", "Gib an, wie viele Ecken diese Pyramide hat.", "Koerper/Ecken-Kanten-Flaechen", 45),
 "Ecken und Kanten": (5, "sicher", "", "Ergaenze die Tabelle. (Quader/Pyramide, Ecken/Kanten)", "Koerper/Ecken-Kanten-Flaechen", 90),
 "Eindeutig": (8, "unsicher", "7/8", "Selina und Jasmin ueben das Loesen von Gleichungen.", "Gleichungen; Teilaufgaben fehlen", 120),
 "Einfache Gleichung": (8, "sicher", "", "Gegeben ist die Gleichung 18−3x=12.", "Lineare Gleichung mit formaler Variable", 60),
 "Eingefärbter Körper": (5, "sicher", "", "besteht aus drei gleich grossen Wuerfeln ... vollstaendig in Farbe getaucht", "Raumvorstellung Wuerfel/Seitenflaechen", 90),
 "Eiscafé": (5, "sicher", "", "jede Kugel Eis 0,80 € ... Eine Portion Sahne kostet 0,50 €", "Sachrechnen mit Geld, Preisvergleich", 150),
 "Fahrradcomputer": (None, "nicht_bestimmbar", "", "Anna hat einen Fahrradcomputer an ihrem Fahrrad.", "Nur ein Satz Stimulus, Teilaufgaben fehlen", 120),
 "Fahrradtour": (6, "unsicher", "6/7", "hat Julia in diesem Saeulendiagramm dargestellt", "Saeulendiagramm auswerten/Manipulation erkennen; Teilaufgaben fehlen", 120),
 "Fahrräder": (5, "sicher", "", "notiert Marko in einer Strichliste", "Daten/Strichliste-Haeufigkeit", 90),
 "Fahrtrichtung geradeaus": (5, "unsicher", "5/6", "Dieses Verkehrszeichen zeigt an", "Vermutlich Achsensymmetrie am Verkehrszeichen; Teilaufgaben fehlen", 60),
 "Faschingsdeko": (6, "unsicher", "5/6", "Schreibe alle moeglichen Farbkombinationen auf.", "Kombinatorik/systematisches Zaehlen (5/6)", 120),
 "Fehlende Zahlen": (7, "sicher", "", "4 + ☐ = -17", "Rechnen mit negativen Zahlen", 90),
 "Fieberthermometer": (6, "unsicher", "5/6", "zeigt die gemessene Koerpertemperatur in Grad Celsius an", "Dezimal-Skala ablesen (Groessen 5 / Dezimalzahlen 6)", 60),
 "Figur aus zwei Dreiecken": (7, "sicher", "", "Sind die beiden Winkel a und d gleich gross?", "Winkelsaetze im Dreieck, Begruendungen pruefen", 150),
 "Fische zählen": (8, "unsicher", "7/8", "p(Fisch mit rotem Punkt fangen) = ... = 250/x", "Wahrscheinlichkeit/Anteile + Verhaeltnisgleichung (Capture-Recapture)", 120),
 "Fliesen": (7, "sicher", "", "50 Platten mit einer Groesse von jeweils 0,16 m²", "Antiproportionaler Zusammenhang (Gesamtflaeche konstant)", 90),
 "Fliesen für den Fußboden": (6, "unsicher", "6/7", "Gib die Seitenlaenge jeder Fliesenart (gross, mittel, klein) an.", "Flaechen/Laengen am Quadrat (6); Teil 2 quadratisches Anzahl-Argument (7)", 180),
 "Flächengleich oder nicht": (7, "unsicher", "7/8", "Ist der Flaecheninhalt der beiden Parallelogramme gleich gross? (EMF-Text)", "Parallelogrammflaeche/Scherung (7/8-Band)", 180),
 "Flächeninhalt": (5, "sicher", "", "Gib den Flaecheninhalt dieser Figur an. ... cm²", "Flaeche auszaehlen/zerlegen (Gitterfigur)", 75),
 "Freibad": (5, "unsicher", "5/6", "Das Diagramm zeigt die Zahlen der Besucherinnen und Besucher", "Diagramm ablesen/auswerten; Teilaufgaben fehlen", 120),
 "Freizeitbeschäftigungen": (5, "unsicher", "5/6", "Abbildung 1 zeigt das Ergebnis dieser Befragung", "Diagramm auswerten; Teilaufgaben fehlen", 120),
 "Freizeitkosten": (None, "nicht_bestimmbar", "", "Hat Dennis Recht? Kreuze an.", "Kontext fehlt komplett (Bezugs-Abbildung/Aussage nicht im Item)", 120),
 "Freunde": (6, "unsicher", "6/7", "Das Diagramm zeigt Informationen zu ihrer Koerpergroesse und zu ihrem Alter.", "Punktdiagramm interpretieren (Daten 6 / funktionales Denken 7)", 120),
 "Frühstücksbrötchen": (5, "unsicher", "5/6", "sechs normale Broetchen zu je 0,35 €", "Sachrechnen Geld (5); Dezimalmultiplikation (6); Teilaufgaben fehlen", 90),
 "fuehrerschein": (6, "unsicher", "6/7", "wie viel Prozent der Theorie-Pruefungen ... nicht bestanden wurden", "Prozentwerte nur ablesen/vergleichen (Daten 6, Prozentkontext 7)", 150),
 "Fußballtabelle": (5, "sicher", "", "Fuer einen Sieg erhaelt eine Mannschaft drei Punkte", "Rechnen mit natuerlichen Zahlen im Kontext", 120),
 "Fußleisten": (5, "sicher", "", "Ein Zimmer, das 4 m lang und 5 m breit ist", "Umfang Rechteck (Fussleisten)", 90),
 "Füllverhalten": (8, "unsicher", "7/8", "Graph enthaelt eine Strecke mit positiver Steigung (Auswertung)", "Fuellgraph/funktionaler Zusammenhang; Aufgabentext nur als Rasterbild", 150),
 "Fünfundvierzig": (5, "unsicher", "5/8", "6 · ☐ + 3 = 45", "Platzhalteraufgabe (Kopfrechnen 5) vs. Gleichungsvorstufe (8)", 60),
 "Geld anlegen": (7, "sicher", "", "Begruendung, die darauf beruht, dass sich bei geaendertem Grundwert auch der Prozentwert aendert (Auswertung)", "Zins-/Prozentrechnung mit Grundwert-Argument", 150),
 "Geometrische Körper erkennen": (5, "sicher", "", "In der nachfolgenden Tabelle sind Koerper benannt.", "Koerper erkennen/benennen", 90),
 "Geraden im Koordinatensystem": (8, "sicher", "", "die Gerade mit der Gleichung y = ½x − 2", "Lineare Funktionen (Nullstelle ablesen)", 60),
 "Gesamtkantenlänge": (5, "sicher", "", "Wie lang sind alle Kanten des Quaders zusammen?", "Quader/Kanten (Koerper)", 75),
 "Geschichte zur Graphik": (7, "unsicher", "7/8", "Kreuze die Beschreibung an, die zu der Graphik passt.", "Qualitativer Graph-Situation-Abgleich (Zuordnungen 7 / Funktionen 8)", 90),
 "Geschwindigkeitsüberschreitung": (5, "sicher", "", "Mit welchem Bussgeld ist jetzt zu rechnen?", "Tabelle ablesen, Differenz natuerlicher Zahlen", 60),
 "Gewerbezone": (6, "unsicher", "5/6", "Hinweis: 1 ha = 10 000 m²", "Flaecheneinheiten umrechnen + Division", 120),
 "Gewitter": (7, "sicher", "", "braucht etwa drei Sekunden, um einen Kilometer zurueckzulegen", "Proportionaler Dreisatz", 150),
 "Gleichung finden": (8, "sicher", "", "Welche der folgenden Gleichungen entspricht dieser Rechnung?", "Gleichung aufstellen und loesen", 120),
 "Gleichung lösen 1": (8, "sicher", "", "Loese die Gleichung 4+x=−6.", "Lineare Gleichung (mit negativen Zahlen)", 45),
 "Gleichung lösen 2": (8, "sicher", "", "Welche Loesung hat die Gleichung 16 – 6x = 14?", "Lineare Gleichung", 60),
 "Gleichung lösen 3": (8, "sicher", "", "Welche Zahl ist Loesung der Gleichung 2x - 4 = 6?", "Lineare Gleichung", 60),
 "Gleichung verändern": (8, "sicher", "", "so, dass die veraenderte Gleichung die Loesung x = 9 hat", "Lineare Gleichungen, Struktureinsicht", 150),
 "Gleichungen lösen ist nicht schwierig": (8, "sicher", "", "Gleichungen koennen auf verschiedene Arten geloest werden.", "Gleichungen loesen; Teilaufgaben fehlen", 120),
 "Glücksrad": (6, "sicher", "", "wies der Zeiger ... 66-mal auf das rote Feld", "Relative Haeufigkeit/Wahrscheinlichkeit", 120),
 "Glücksrad drehen": (6, "sicher", "", "treten diese Ergebnisse mit folgenden Wahrscheinlichkeiten p ein", "Wahrscheinlichkeitsverteilung (Summe 1)", 120),
 "Glückssäckchen": (8, "unsicher", "6/8", "Welcher Term gibt die Wahrscheinlichkeit an?", "Anteilsvergleich (6), aber Teil 3 verlangt Term mit Variablen (8)", 240),
 "Großer Wagen": (5, "sicher", "", "zeichnet 6 Sterne ... vereinfacht in ein Koordinatensystem", "Koordinatensystem/Punkte", 120),
 "Gummibären": (6, "unsicher", "6/7", "Je ein Sechstel gruene, gelbe, weisse und orangefarbene Baeren und ein Drittel rote", "Brueche/Anteile (6); Teil 2 mit Hochrechnung ueber Gewicht (7)", 180),
 "Güterverkehr": (7, "unsicher", "6/7", "den Zusammenhang zwischen den Kosten ... und der Laenge des Transportweges", "Graphen mehrerer Zuordnungen ablesen/vergleichen", 120),
 "Handygebühr": (8, "sicher", "", "Kreuze die passende Gleichung an. y = 0,09 · x + 5", "Lineare Funktion aus Sachkontext", 150),
 "Harzwanderung": (None, "nicht_bestimmbar", "", "Peter und Markus planen eine Wanderung durch den Harz.", "Nur ein Satz Stimulus, Teilaufgaben fehlen", 120),
 "Hauptstädte": (6, "sicher", "", "In der linken unteren Ecke ist der Massstab dieser Karte angegeben.", "Massstab/Groessen (Karte)", 150),
 "Hausaufgaben": (6, "sicher", "", "sollen in einer Haeufigkeitstabelle dargestellt werden", "Haeufigkeitstabelle + Kreisdiagramm (Daten)", 240),
 "Haushaltsabfälle": (5, "sicher", "", "In welchem Bundesland gab es die wenigsten Haushaltsabfaelle pro Einwohner?", "Diagramm ablesen", 120),
 "Heizkosten": (7, "sicher", "", "bis zu 40 % ... um weitere 30 % reduziert", "Verkettete Prozentrechnung", 90),
 "Hochrad": (8, "sicher", "", "Vorderrad (Durchmesser: 1,56 m) ... legt man eine Strecke von etwa 4,90 m zurueck", "Kreisumfang", 150),
 "Holzstab": (5, "sicher", "", "Ein 3 m langer Holzstab wird in zwei gleich lange Teile zersaegt.", "Groessen/Laengen halbieren", 45),
 "Holzwürfel": (6, "unsicher", "5/6", "wie viele verschiedene Moeglichkeiten es gibt ... einen Dreierturm zu bauen", "Kombinatorik/Permutationen (5/6)", 90),
 "Honigbiene": (5, "sicher", "", "Wie lang ist diese Biene ungefaehr?", "Groessenvorstellung Laenge", 45),
 "Hälfte": (5, "sicher", "", "Wie viel ist die Haelfte von 1 Million?", "Grosse Zahlen/Stellenwert", 45),
 "Im Kreis laufen": (8, "unsicher", "7/8", "Welcher Graph passt am besten, um diese Bewegung darzustellen?", "Qualitativer funktionaler Zusammenhang (nichtlinear)", 90),
 "Inliner": (7, "sicher", "", "faehrt sie mit einer Geschwindigkeit von 12 km/h weiter", "Geschwindigkeit/proportionale Zuordnung", 150),
 "Innenwinkel": (None, "nicht_bestimmbar", "", "", "Keine Aufgabendaten (nur GeoGebra-Datei, kein Stamm extrahierbar)", None),
 "Innenwinkel 2": (7, "sicher", "", "betraegt die Summe der drei Innenwinkelgroessen 180°", "Winkelsaetze (Innenwinkelsumme)", 120),
 "Internetauktion": (6, "sicher", "", "Gib den durchschnittlichen Preis der neun Notebooks an.", "Kenngroessen: Spannweite + arithmetisches Mittel", 150),
 "Jeans mit Ermäßigung": (7, "sicher", "", "mit 20 % Ermaessigung angeboten. Der neue Preis betraegt nun 48,00 €", "Prozentrechnung (Grundwert gesucht)", 60),
 "Joggen": (7, "sicher", "", "mindestens 65 % vom Maximalpuls", "Prozentrechnung im Sachkontext", 120),
 "Jubiläumsgeschenk": (8, "sicher", "", "Gib eine Gleichung an, wie sich y aus x berechnen laesst.", "Lineare Funktion/Gleichung aus Sachkontext (y=3x+2)", 180),
 "Judomatte": (5, "sicher", "", "innerhalb einer 8 m x 8 m grossen quadratischen Kampfzone", "Flaeche Quadrat", 45),
 "Kauf eines DVD-Players": (7, "sicher", "", "um 20 % reduziert ... nochmal einen Rabatt von 5 %", "Verkettete Prozentrechnung", 210),
 "Kaum eine Chance": (6, "sicher", "", "Gib die Wahrscheinlichkeit an, mit der Enrico bei seinem ersten Wurf eine Sechs wirft", "Laplace-Wahrscheinlichkeit + Unabhaengigkeits-Argument", 120),
 "Kopf und Körper": (7, "unsicher", "6/7", "die Laenge des Kopfes zur gesamten Koerpergroesse ungefaehr im Verhaeltnis 1:4", "Verhaeltnisrechnung", 120),
 "Kraftfutter": (7, "sicher", "", "Der Kraftfuttervorrat reicht fuer fuenf Nashoerner sechs Wochen.", "Antiproportionaler Dreisatz", 90),
 "Kreise färben": (7, "sicher", "", "Faerbe 20 % dieser Kreise ein.", "Prozent-Grundvorstellung (Anteil bestimmen)", 60),
 "Kreise und Vierecke": (None, "nicht_bestimmbar", "", "Gegeben ist jeweils ein Kreis mit dem Radius r = 3 cm.", "Teilaufgaben fehlen — zwischen Kreis zeichnen (6) und Kreisberechnung (8) nicht entscheidbar", 120),
 "Kreisfiguren": (8, "unsicher", "7/8", "Figuren, die durch Kreislinien und Strecken begrenzt sind", "Flaechenvergleich an Kreisfiguren (Kreis Kl. 8; ggf. Zerlegungsargument 7)", 120),
 "Kugeln ziehen": (8, "unsicher", "7/8", "dass die Wahrscheinlichkeit eine rote Kugel zu ziehen 20 % betraegt", "Wahrscheinlichkeit + Anteils-/Verhaeltnisschluss", 120),
 "Körper füllen": (6, "sicher", "", "ist mit einigen kleinen 1-cm³-Wuerfeln gefuellt", "Volumen Quader (Einheitswuerfel)", 75),
 "Körper mit Seitenflächen": (5, "unsicher", "5/6", "deren Oberflaeche aus ebenen Vielecken besteht", "Koerper/Polyeder-Eigenschaften; Teilaufgaben fehlen", 120),
 "Lage der Würfel": (5, "sicher", "", "Die Augenzahlen gegenueberliegender Seiten ergaenzen sich immer zu 7.", "Raumvorstellung Wuerfel", 180),
 "Lage von zwei Geraden": (8, "sicher", "", "y = 4x + 3 ... y = 4x − 3. Welche Lage haben diese Geraden?", "Lineare Funktionen (Steigung/Parallelitaet)", 90),
 "Leistung des Motors": (7, "unsicher", "6/7", "1 kW sind etwa 1,36 PS", "Umrechnung mit Faktor/proportionaler Vergleich", 90),
 "Liebstes Schulfach": (5, "sicher", "", "Die Tabelle zeigt das Ergebnis der Umfrage.", "Daten/Tabelle auswerten", 90),
 "Linear und proportional": (8, "sicher", "", "Jede lineare Funktion kann durch eine Funktionsgleichung der Form y = mx + b beschrieben werden.", "Lineare Funktionen", 120),
 "Lineare Funktionen anwenden": (8, "sicher", "", "Diese Zuordnungen lassen sich durch Gleichungen darstellen.", "Lineare Funktionen im Sachkontext", 180),
 "Literberechnungen": (6, "sicher", "", "wie viel ¾ von 10 Liter sind", "Bruchteil von Groessen", 60),
 "Lohnerhöhung": (7, "sicher", "", "Gib an, um wie viel Prozent der Lohn erhoeht wird.", "Prozentsatz berechnen", 90),
 "Luftballons": (6, "sicher", "", "Wie gross ist die Wahrscheinlichkeit, dass er einen roten Luftballon erhaelt?", "Laplace-Wahrscheinlichkeit einstufig", 60),
 "Mathematikarbeit": (7, "sicher", "", "48 von 60 Punkten erreicht, das sind ... der Gesamtpunktzahl", "Prozentsatz berechnen", 60),
 "Mauer aus Zahlen": (7, "unsicher", "5/7", "Zahlenmauer: oben 48, unten 3, -4, x", "Multiplikative Zahlenmauern mit negativen Zahlen (7); Grundprinzip 5", 180),
 "Maus": (5, "sicher", "", "Welche der folgenden Masseinheiten passt hier zur Masszahl 40?", "Groessenvorstellung/Einheiten", 45),
 "Maßstabsleiste": (6, "sicher", "", "Welcher Massstab passt dazu?", "Massstab", 75),
 "Maßstabsrechner": (6, "sicher", "", "Ein Massstab gibt das Groessenverhaeltnis von Bild zu Original an.", "Massstab; Teilaufgaben fehlen", 90),
 "Mensch ärgere dich nicht": (6, "sicher", "", "Gib die Wahrscheinlichkeit an, dass ein Spieler gleich beim ersten Wuerfeln eine Sechs hat.", "Laplace-Wahrscheinlichkeit + Gleichwahrscheinlichkeits-Argument", 120),
 "Messzylinder": (5, "unsicher", "5/6", "Gib an, wie viel Fluessigkeit sich in diesem Messzylinder befindet.", "Skala ablesen (Groessen 5/Dezimalskala 6)", 60),
 "Mitte zwischen Zahlen": (6, "sicher", "", "genau in der Mitte der beiden Zahlen 6,06 und 6,6", "Dezimalzahlen ordnen/Mittelwert", 75),
 "Muckibude": (5, "sicher", "", "Die Grafik zeigt die Mitgliederzahlen", "Diagramm ablesen", 120),
 "Mädchenanteil": (6, "sicher", "", "Wie gross ist der Anteil der Maedchen in der gesamten Klasse?", "Anteile/Brueche", 60),
 "Mülltonne": (6, "unsicher", "6/8", "Ermittle, welches Volumen diese Muelltonne etwa hat.", "Volumen schaetzen/modellieren (Quadermodell 6, Zylindermodell 8+)", 180),
 "Nachfolgerzahl": (8, "unsicher", "7/8", "Quadriere beide Zahlen und ziehe das kleinere Ergebnis vom groesseren ab.", "Termumformung/allgemeines Begruenden; Teilaufgaben fehlen", 180),
 "Nagelbrett": (5, "unsicher", "5/6", "Rechtecke gespannt werden ... Quadrat mit einem Flaecheninhalt von 16 cm²", "Rechteckflaechen am Geobrett; Teilaufgaben fehlen", 150),
 "Naschkatze": (5, "sicher", "", "In welchem Quartal betrug der Umsatz 14 000 Euro?", "Diagramm ablesen", 60),
 "Nashorn": (7, "unsicher", "6/7", "hatte zu diesem Zeitpunkt eine Schulterhoehe von 60 cm (im Bild als Doppelpfeil eingezeichnet)", "Verhaeltnis/Massstab am Foto", 150),
 "Nebenjob": (7, "unsicher", "5/7", "Er verdient in einer Stunde 12 Euro.", "Vermutlich proportionale Zuordnung; Teilaufgaben fehlen", 120),
 "Niederschlag": (6, "unsicher", "6/7", "Gib die Spannweite ... der durchschnittlichen Temperaturen an.", "Klimadiagramm auswerten + Kenngroessen (6/7-Grenze)", 240),
 "Niederschläge": (6, "unsicher", "6/7", "Gib die Spannweite ... der monatlichen Niederschlagsmengen an.", "Diagramm auswerten + Kenngroessen (6/7-Grenze)", 240),
 "Null Komma Acht": (6, "sicher", "", "Ergaenze jeweils die fehlende Zahl: 8:☐=0,8 (EMF-Text)", "Dezimalzahlen dividieren (Struktureinsicht)", 120),
 "Ohrhänger": (5, "sicher", "", "Wie viele solche Ohrhaenger kann Janina mit 90 cm Silberdraht herstellen?", "Sachrechnen Laengen (Umfang gleichseitiges Dreieck)", 240),
 "Osterhase": (6, "unsicher", "6/7", "1 cm³ Schokolade wiegt 1,3 g.", "Dezimaldivision/Groessen (6); Aussagen mit 400 % (7)", 180),
 "Papier": (7, "sicher", "", "500 Blatt einer Papiersorte sind 55mm hoch. ... wie hoch 200 Blatt", "Proportionaler Dreisatz", 90),
 "Pappschachtel": (6, "unsicher", "6/7", "Wie gross ist das Volumen der Schachtel?", "Volumen Quader (6); Faltproblem raeumlich (7)", 150),
 "Parfum": (7, "unsicher", "6/7", "werden mit jedem Pumpstoss durchschnittlich 0,2 ml Parfum verteilt", "Proportionales Hochrechnen/Modellieren mit Dezimalzahlen", 210),
 "Parkhaus": (7, "unsicher", "7/8", "Die Parkgebuehren fuer 0 bis 11 Stunden sollen grafisch dargestellt werden.", "Zuordnung als (Stufen-)Graph darstellen", 180),
 "Parlamentswahl": (7, "sicher", "", "Davon fielen 42 % auf den Kandidaten Herrn Aal.", "Prozentwert berechnen", 90),
 "Passende Schuhe": (7, "sicher", "", "Wie viel Grad muss der Kreisausschnitt ... haben?", "Prozentrechnung + Kreisdiagramm (Winkel)", 210),
 "Pflaumen": (7, "unsicher", "5/7", "1kg Pflaumen kostet 1,90€. ... wie viel 500g Pflaumen kosten", "Proportionaler Schluss (7), als Halbieren auch Groessen (5)", 60),
 "Pinsel": (6, "sicher", "", "Der Pinsel in Abbildung 1 ist im Massstab 1:3 abgebildet.", "Massstab", 150),
 "Plättchen ziehen": (6, "sicher", "", "Gib die Wahrscheinlichkeit dafuer an, dass Ellen ein Plaettchen mit einem A zieht.", "Laplace-Wahrscheinlichkeit einstufig", 60),
 "Prozentanteil schätzen": (7, "sicher", "", "Wie viel Prozent der Kreisflaeche sind grau gefaerbt?", "Prozent-Grundvorstellung (Anteil schaetzen)", 45),
 "Punkt gesucht": (7, "unsicher", "7/8", "von den Punkten A und B den gleichen Abstand hat", "Ortslinien (Mittelsenkrechte/Kreis)", 180),
 "Punkte auf Geraden": (8, "sicher", "", "Weise nach: Der Punkt A(4|3) liegt auf der Geraden (EMF-Text)", "Lineare Funktionen (Punktprobe, Parameter b)", 240),
 "Punkte im Koordinatensystem": (5, "sicher", "", "Koordinatengitter mit Punkten A, B, C (EMF-Text)", "Koordinatensystem/Punkte ablesen, Spiegelung", 120),
 "Punktgenau": (7, "unsicher", "5/7", "Welche Koordinaten hat der Punkt P? P(-2|1) (EMF-Text)", "Koordinatensystem mit negativen Koordinaten (alle vier Quadranten)", 90),
 "Pyramidenbau": (5, "unsicher", "5/6", "In Abbildung 2 wurde mit Staeben und Kugeln das Netz dieser Pyramide gelegt.", "Netz einer Pyramide/Raumvorstellung", 120),
 "Quader": (6, "unsicher", "5/6", "Die Abbildung zeigt einen Holzquader. (EMF: 4/5/6 cm)", "Vermutlich Volumen/Oberflaeche Quader; Teilaufgaben fehlen", 120),
 "Quadernetz": (5, "sicher", "", "Kreuze jeweils an, ob es sich um das Netz eines Quaders handelt.", "Netze von Quadern", 90),
 "Quadernetz 2": (5, "sicher", "", "Welche der folgenden Abbildungen zeigt das Netz eines Quaders?", "Netze von Quadern", 60),
 "Quadernetz vervollständigen": (5, "sicher", "", "Ergaenze in der Zeichnung fehlende Flaechen, so dass ein vollstaendiges Quadernetz entsteht.", "Netze von Quadern", 120),
 "Quadrat im Gitter": (7, "unsicher", "5/7", "Auf das Gitterpapier ist ein Quadrat gezeichnet. ... Du darfst auch Hilfslinien einzeichnen.", "Schraeges Quadrat: Flaeche durch Zerlegung (7) oder geschicktes Auszaehlen (5)", 120),
 "Quadrat im Koordinatensystem": (7, "unsicher", "5/7", "B (4|-2), C (4|3) und D (-1|3)", "Koordinatensystem mit negativen Koordinaten", 90),
 "Quadrat und Raute": (None, "nicht_bestimmbar", "", "Gegeben ist eine Gerade, die durch den Ursprung ... verlaeuft.", "Teilaufgaben fehlen — Anker nicht entscheidbar", 120),
 "Quadrat zeichnen": (5, "sicher", "", "Zeichne ein Quadrat mit der Seitenlaenge 5 cm.", "Grundkonstruktion Quadrat", 90),
 "Quadratdifferenz": (8, "unsicher", "7/8", "Das Ergebnis ist die Summe der beiden Zahlen 5 und 4.", "Termumformung/Begruendung (a²−b²); Teilaufgaben fehlen", 180),
 "Quadrate": (5, "unsicher", "5/7", "Wo muss der vierte Punkt C liegen, damit ein Quadrat ABCD entsteht?", "Koordinatensystem/Quadrat ergaenzen (Quadranten unklar)", 90),
 "Quadratfläche": (5, "sicher", "", "Bestimme den Flaecheninhalt des gegebenen Quadrats.", "Flaeche Quadrat (messen + berechnen)", 90),
 "Rabattaktion": (7, "sicher", "", "dass die Kunden die Mehrwertsteuer von 19 % praktisch nicht bezahlen muessen", "Prozentrechnung (vermehrter/verminderter Grundwert)", 90),
 "Raten beim Test": (8, "sicher", "", "dass Christian bei allen vier Fragen des Tests die richtigen Antworten ankreuzt", "Mehrstufiger Zufallsversuch (Pfadmultiplikation)", 150),
 "Rathausuhr": (5, "sicher", "", "Der hohe Glockenton erklingt zur Viertelstunde einmal", "Systematisches Zaehlen/Rechnen mit natuerlichen Zahlen", 150),
 "Rauminhalt von Prismen": (8, "sicher", "", "Die Rauminhalte der zwei Koerper A und B sollen verglichen werden", "Volumen von Prismen", 90),
 "Rauten": (7, "unsicher", "7/8", "Die Diagonalen AxCx dieser Rauten sind 2 cm lang.", "Rautenflaeche (Diagonalen) im Koordinatensystem, Verallgemeinerung als Term (8)", 300),
 "Rechenvorteil": (6, "unsicher", "5/6", "4 · 3,15 · 25", "Rechengesetze/Kommutativitaet (5) mit Dezimalzahl (6)", 90),
 "Rechteck": (5, "unsicher", "5/7", "dass das Viereck ABCD ein Rechteck ist", "Punkt im Koordinatensystem ergaenzen (Quadranten unklar)", 90),
 "Rechtskurve": (8, "unsicher", "7/8", "Er bremst vor der Kurve etwas ab (fehlgeparster Lizenzhinweis = Aufgabentext)", "Qualitativer Geschwindigkeits-Zeit-Graph", 90),
 "Regelmäßige Vielecke": (5, "sicher", "", "Zeichne in dem gegebenen gleichseitigen Dreieck alle Symmetrieachsen ein.", "Achsensymmetrie", 90),
 "Reiseverlauf": (7, "sicher", "", "zeigt vereinfacht den Reiseverlauf von zwei Fahrzeugen A und B", "Weg-Zeit-Diagramm interpretieren", 150),
 "Restaurantgewinnspiel": (6, "sicher", "", "muss eine Zahl zwischen 1 und 100 nennen und dann ... eine Kugel ziehen", "Laplace-Wahrscheinlichkeit einstufig", 90),
 "Richtig umgeformt": (7, "unsicher", "7/8", "Wandle den Term 2x+4a in ein Produkt um (EMF-Text)", "Terme umformen (Faktorisieren/Ausmultiplizieren)", 120),
 "Rollrasen": (6, "unsicher", "5/6", "Diese neue Rasenflaeche ist 11 m lang und 10,5 m breit.", "Rechteckflaeche mit Dezimalzahlen; Teilaufgaben fehlen", 150),
 "Rolltreppe": (7, "unsicher", "7/8", "Das folgende Zeit-Hoehen-Diagramm stellt dar, wie tief sie ... noch unter der Erde ist.", "Funktionsgraph interpretieren; Teilaufgaben fehlen", 120),
 "Rot, gelb, grün": (6, "sicher", "", "In einer Urne liegen drei rote, vier gelbe und fuenf gruene Kugeln.", "Laplace-Wahrscheinlichkeit einstufig (mit Zuruecklegen)", 120),
 "Rubbellose": (6, "unsicher", "6/7", "Die Baeckerei laesst 7500 Lose drucken. 25 davon haben 3 Fussballbilder.", "Wahrscheinlichkeit als Anteil + Bruchteil-Rechnung", 180),
 "Rundfunkgebühren": (7, "unsicher", "6/7", "Herr Kunze hat sich genauer mit den Daten befasst und viel gerechnet.", "Daten/Tabelle + vermutlich Prozent-/Differenzrechnung; Teilaufgaben fehlen", 180),
 "Räumungsverkauf": (7, "sicher", "", "die bereits um 25 % reduzierten Preise nochmals um 25 %", "Verkettete Prozentrechnung", 240),
 "Sauerkraut": (7, "unsicher", "7/9", "die sich taeglich um 70 % gegenueber der Vortagsmenge vermehren", "Wiederholte Prozentrechnung (7); exponentielle Sicht (9)", 150),
 "Schachteln packen": (6, "unsicher", "5/6", "Die Kanten der mittleren Schachtel sind 1 cm laenger als die doppelte Kantenlaenge", "Kantenlaengen-Rechnung (5) + raeumliches Packen (6)", 240),
 "Schlüssel": (6, "sicher", "", "Wie gross ist die Wahrscheinlichkeit, dass die Haustuer mit dem ersten Schluessel aufgeht?", "Laplace-Wahrscheinlichkeit einstufig", 45),
 "Schneekristalle": (5, "sicher", "", "Wie viele Symmetrieachsen hat dieser Schneekristall?", "Achsensymmetrie", 60),
 "Schnittpunkt von Graphen": (8, "sicher", "", "g(x) = 2x − 1 und f(x) = −x + 2 ... Koordinaten des Schnittpunkts", "Lineare Funktionen (Schnittpunkt/Gleichsetzen)", 120),
 "Schokoladenbonbons": (6, "sicher", "", "Gib die Wahrscheinlichkeit dafuer an, bei der ersten Entnahme ein Bonbon mit weisser Schokoladenfuellung zu bekommen.", "Laplace-Wahrscheinlichkeit + Anteilsvergleich", 150),
 "Schokoladenfiguren": (6, "unsicher", "6/7", "Das Kreisdiagramm zeigt die Anteile", "Kreisdiagramm/Anteile; Teilaufgaben fehlen", 120),
 "Schokoladenpreis": (7, "sicher", "", "die Zuordnung der zwei Groessen Schokoladenmenge (in g) → Schokoladenpreis (in €)", "Proportionale Zuordnung am Graphen", 150),
 "Schokolinsen": (5, "unsicher", "5/7", "Auf dem Foto siehst du sehr viele Schokolinsen.", "Schaetzen/Zaehlstrategie (5) bis Modellieren ueber Flaechen (7); Frage fehlt", 180),
 "Schrankbreiten": (5, "sicher", "", "Stelle eine Schrankkombination von 135 cm Breite zusammen.", "Systematisches Probieren/Rechnen mit natuerlichen Zahlen", 150),
 "Schulgrundstück": (6, "unsicher", "6/7", "Die Abbildung zeigt das Luftbild einer Schule.", "Vermutlich Flaechenschaetzung mit Massstab; Teilaufgaben fehlen", 150),
 "Schulkleidung": (7, "unsicher", "6/7", "haben 9018 (50,6 %) der Befragten mit ja geantwortet", "Daten + Prozentangaben; Teilaufgaben fehlen", 150),
 "Schulstatistik": (5, "sicher", "", "Im Diagramm ist dargestellt, wie viele Schulen es ... gab", "Diagramm ablesen", 90),
 "Schwarz-Weiß-Würfel": (6, "sicher", "", "sind die Seiten mit den Augenzahlen 1 und 6 schwarz gefaerbt", "Laplace-Wahrscheinlichkeit (Ereignis aus mehreren Ergebnissen)", 90),
 "Skala und Zahlen": (5, "unsicher", "5/6", "Zwei Zahlen sind auf dem obigen Ausschnitt der Zahlengeraden markiert.", "Zahlengerade ablesen (Skalierung unbekannt: nat. Zahlen 5 / Dezimal 6)", 90),
 "Spielwürfel": (6, "sicher", "", "einen fairen 20-seitigen Spielwuerfel ... Wahrscheinlichkeit dafuer, dass die Zahl 11 geworfen wird", "Laplace-Wahrscheinlichkeit einstufig", 150),
 "Sprechstunde": (5, "sicher", "", "notiert an einem Vormittag, wie viele Maedchen und Jungen zur Sprechstunde kamen", "Daten/Liste auswerten", 120),
 "Stammbrüche untersuchen": (6, "sicher", "", "Ein Bruch mit einer 1 im Zaehler ... heisst Stammbruch.", "Brueche vergleichen/ordnen", 120),
 "Steile Straße": (7, "sicher", "", "dass die Strasse dort ein Gefaelle von 12 % hat", "Prozentrechnung im Steigungs-Kontext (inkl. 45°-Argument)", 270),
 "Sterne und Sandkörner": (5, "unsicher", "5/8", "70 Trilliarden = 7 · 10^___", "Grosse Zahlen/Zahlwoerter (5); Zehnerpotenz-Schreibweise (8)", 180),
 "Strecke im Koordinatenkreuz": (5, "unsicher", "5/7", "Die Strecke AD soll an der y-Achse gespiegelt werden.", "Koordinatensystem + Achsenspiegelung; Loesung enthaelt negative Koordinaten (7)", 180),
 "Streichholzziehen": (6, "sicher", "", "Wie gross ist die Wahrscheinlichkeit, dass er das kurze Streichholz zieht?", "Laplace-Wahrscheinlichkeit einstufig", 60),
 "Suche die Zahl": (5, "sicher", "", "5 × ☐ = 10   3 × ☐ = 24", "Platzhalteraufgaben/Einmaleins-Umkehrung", 60),
 "Säulenhöhe": (6, "sicher", "", "Gib die durchschnittliche Hoehe dieser drei Saeulen an.", "Arithmetisches Mittel (auch rueckwaerts)", 150),
 "Tabelle": (7, "unsicher", "7/8", "Die Tabelle zeigt einen Zusammenhang zwischen a und b.", "Zuordnung als Gleichung/Term erkennen", 90),
 "Tabelle ausfüllen": (7, "sicher", "", "Die Tabelle zeigt eine proportionale Zuordnung.", "Proportionale Zuordnung", 60),
 "Tankinhalt": (7, "sicher", "", "den aktuellen Durchschnittsverbrauch in Liter pro 100 km", "Proportionaler Zusammenhang (Verbrauch)", 120),
 "Temperatur": (7, "unsicher", "7/8", "Gib eine Formel fuer die Umrechnung von Temperaturen in °C nach °F an.", "Formel anwenden (7) und selbst aufstellen (lineare Formel, 8)", 150),
 "Temperaturdifferenz": (7, "sicher", "", "misst Tim morgens ... -1°C. Am Nachmittag ... 18°C", "Negative Zahlen (Differenz ueber Null hinweg)", 60),
 "Temperaturen in Frankfurt am Main": (6, "unsicher", "6/7", "die langjaehrigen Durchschnittstemperaturen der einzelnen Monate", "Tabelle/Diagramm + Kenngroessen; Teilaufgaben fehlen", 150),
 "Thermometer": (7, "sicher", "", "Spaeter zeigt das Thermometer -3°C. Danach steigt die Temperatur um 15 Grad. (EMF-Text)", "Negative Zahlen/Temperatur", 120),
 "Tombola zum Schulfest": (6, "sicher", "", "befinden sich 200 Lose in einem Gefaess. Davon sind 70 kleine Gewinne", "Laplace-Wahrscheinlichkeit einstufig", 120),
 "Traktor": (6, "sicher", "", "Spielzeugmodelle in den folgenden Massstaeben ... Bei welchem Massstab ist das Modell am kleinsten?", "Massstab", 60),
 "Trapez ohne Symmetrie": (6, "unsicher", "5/6", "Das dargestellte Trapez hat keine Symmetrieachse.", "Symmetrie/Viereckseigenschaften begruenden", 120),
 "Trapezvariation": (7, "unsicher", "7/8", "A = (a + c) · h / 2", "Trapezflaechenformel/Termverhalten (7/8-Band)", 180),
 "Treppenmaße": (8, "sicher", "", "Schrittmassregel: 2 · h + b = 63 cm", "Formel/Gleichung anwenden und umstellen", 300),
 "Tropfender Wasserhahn": (7, "unsicher", "6/7", "Er faengt das gleichmaessig tropfende Wasser in einem Messbecher auf.", "Proportionales Hochrechnen; Teilaufgaben fehlen", 150),
 "Tunnelbohrmaschine": (7, "unsicher", "6/7", "schafft durchschnittlich 10 m Tunnellaenge in 24 Stunden", "Proportionaler Dreisatz; Teilaufgaben fehlen", 120),
 "Umfang und Fläche": (5, "sicher", "", "Gib an, wie lang der Umfang der dick umrandeten Figur ist. (EMF-Text)", "Umfang/Flaeche im Einheitsgitter", 150),
 "Unfertiger Würfel": (5, "sicher", "", "aus kleinen Wuerfeln der Kantenlaenge 1 cm einen grossen Wuerfel zusammenzusetzen", "Raumvorstellung Wuerfelgebaeude", 150),
 "Ungewöhnlicher Mittelwert": (None, "nicht_bestimmbar", "", "", "Kein Aufgabentext, kein Quell-Extract vorhanden", None),
 "Ungewöhnlicher Spielwürfel": (5, "unsicher", "5/6", "entstand, indem aus einem wuerfelfoermigen Koerper ein Viertel herausgeschnitten wurde", "Raumvorstellung/Ansichten; Teilaufgaben fehlen", 120),
 "Ungleichung erfüllen": (8, "unsicher", "7/8", "Gib drei natuerliche Zahlen fuer z an, so dass die Ungleichung erfuellt ist.", "Ungleichung (die Ungleichung selbst fehlt im Item!)", 90),
 "Unregelmäßiges Viereck": (7, "unsicher", "7/8", "fuer das es keine Formel zur direkten Berechnung des Flaecheninhalts gibt", "Flaechenbestimmung durch Zerlegung (Dreiecksflaechen)", 240),
 "Verbindungsstrecken": (6, "unsicher", "5/6", "So entstehen sechs verschiedene Verbindungsstrecken.", "Systematisches Zaehlen/Kombinatorik", 150),
 "Verkehrszeichen": (5, "sicher", "", "Ist das Bild des Verkehrszeichens achsensymmetrisch?", "Achsensymmetrie", 90),
 "Verlauf des Graphen": (8, "sicher", "", "Pruefe, ob die Aussagen ueber die Gerade y=5x−5 wahr oder falsch sind (EMF-Text)", "Lineare Funktionen (Steigung/Achsenschnitte, auch allgemein)", 150),
 "Verschiedene Rechtecke": (7, "unsicher", "7/8", "zeigt Breiten und Laengen von Rechtecken, die alle den Flaecheninhalt 36 cm² haben", "Antiproportionaler Zusammenhang am Graphen", 210),
 "Viele Brötchen": (7, "unsicher", "5/7", "kostet ein Broetchen 0,30 €, egal wie viele Broetchen man kauft", "Proportionale Zuordnung als Tabelle (7); reines Vervielfachen (5)", 120),
 "Volumenverkleinerung": (9, "unsicher", "8/9", "Das Volumen des neuen Wuerfels ist um ca. 27 % geringer", "Prozent + Volumen-Kanten-Zusammenhang (kubischer Rueckschluss); Teilaufgaben fehlen", 150),
 "Von links wie von rechts": (6, "unsicher", "5/6", "Wie viele verschiedene 4-stelligen Palindromzahlen gibt es?", "Systematisches Zaehlen/Kombinatorik", 180),
 "Waage": (5, "sicher", "", "Die Gewichte sollen nach ihrer Groesse geordnet werden.", "Groessen ordnen, Differenz", 120),
 "Wahl": (7, "sicher", "", "24 Millionen Menschen gingen zur Wahl. Wie viele Menschen haben demnach die Partei A gewaehlt?", "Prozentrechnung + Diagramm", 150),
 "Wahrscheinlicher": (6, "sicher", "", "Welches der beiden Ereignisse hat die hoehere Wahrscheinlichkeit?", "Wahrscheinlichkeiten vergleichen (Muenze/Wuerfel)", 90),
 "Weitsprung": (6, "sicher", "", "laesst fuer jeden Schueler die mittlere Weite berechnen", "Arithmetisches Mittel", 120),
 "Werbelotterie": (8, "sicher", "", "die Wahrscheinlichkeit, das Kuerzel TAA in der richtigen Reihenfolge zu ziehen, wenn die Kugeln nicht zurueckgelegt werden", "Mehrstufiger Zufallsversuch (mit/ohne Zuruecklegen)", 180),
 "Werbemarkt": (7, "unsicher", "7/8", "Gib unter dieser Voraussetzung eine Prognose ab", "Trend aus Diagramm fortschreiben (Zuordnungen/lineares Denken)", 150),
 "Wettkampf wählen": (5, "sicher", "", "entscheiden durch Abstimmung, in welcher Sportart ihr Wettkampf ausgetragen werden soll", "Daten/Haeufigkeiten auswerten", 90),
 "Winkel Gamma": (7, "unsicher", "7/8", "Dann ist g = g1 + g2 ein rechter Winkel.", "Winkelsaetze/Basiswinkel, Beweisschritte ordnen", 240),
 "Winkel im Dreieck": (7, "sicher", "", "b ist doppelt so gross wie a, g ist dreimal so gross wie a (EMF-Text)", "Innenwinkelsumme + einfaches Aufloesen", 90),
 "Winkel im Parallelogramm": (7, "unsicher", "7/8", "Die Seite CD ... wird gedanklich auf der Geraden h hin und her verschoben.", "Parallelogramm/Umfangs-Argument (Extremfall 90°)", 180),
 "Winkel messen": (6, "sicher", "", "Miss die Groesse des Winkels a.", "Winkel messen", 60),
 "Winkelwürfel": (6, "sicher", "", "Mit diesem Winkelwuerfel wurde 1000-mal gewuerfelt.", "Relative Haeufigkeit als Wahrscheinlichkeitsschaetzung", 240),
 "Wo liegt C": (5, "unsicher", "5/6", "Ergaenze einen Punkt C1 ... so, dass ein Dreieck ABC1 mit einem rechten Winkel entsteht (EMF-Text)", "Koordinatensystem + rechter Winkel (senkrechte Geraden)", 150),
 "Wo sind die Punkte": (None, "nicht_bestimmbar", "", "In einem Koordinatensystem ist eine Gerade g eingezeichnet.", "Teilaufgaben fehlen — zwischen Punkte ablesen (5) und linearer Funktion (8) nicht entscheidbar", 120),
 "Wundersame Rechenergebnisse": (5, "unsicher", "5/8", "306 · 1001 = 306306", "Stellenwert-Muster (5); allgemeines Begruenden ggf. Terme (8); Teilaufgaben fehlen", 150),
 "Würfelbau": (5, "sicher", "", "Marco hat kleine Wuerfel aufgestapelt und dann so miteinander verklebt", "Raumvorstellung Wuerfelgebaeude", 120),
 "Würfelkörper": (5, "unsicher", "5/6", "Jeder der kleinen Wuerfel hat ein Volumen von 1 cm³.", "Wuerfelgebaeude zaehlen (5) / Volumenbegriff (6); Teilaufgaben fehlen", 120),
 "Würfeln mit Quader": (6, "sicher", "", "Nach 1000-fachem Werfen des Quaders ergab sich folgende Haeufigkeitstabelle", "Relative Haeufigkeit (Nicht-Laplace-Wuerfel)", 90),
 "Würfeln mit zwei Würfeln": (6, "unsicher", "6/8", "sind alle moeglichen Ergebnisse beim Wuerfeln mit zwei Wuerfeln angegeben", "Ergebnisraum gegeben (6); zweistufige Wahrscheinlichkeit (8); Teilaufgaben fehlen", 150),
 "Würfelnetze": (5, "sicher", "", "handelt es sich um das Netz (Abwicklung) eines Wuerfels?", "Netze von Wuerfeln", 60),
 "Würfeloberfläche": (7, "unsicher", "7/8", "Die Kantenlaenge eines Wuerfels wird halbiert. Um wie viel Prozent verkleinert sich ... seine Oberflaeche?", "Oberflaeche Wuerfel + Prozent (quadratischer Zusammenhang)", 150),
 "Würfelturm": (7, "unsicher", "5/7", "Gib eine Vorschrift (Formel) an, mit der man die Anzahl A(n) ... berechnen kann.", "Zaehlen am Wuerfelturm (5); Term aufstellen (7)", 240),
 "Würfelturm 2": (8, "unsicher", "6/8", "Die darueber stehenden Wuerfel haben immer die halbe Kantenlaenge", "Volumenverhaeltnisse/Potenzen (8er-Potenzen)", 240),
 "Zahl gesucht": (8, "sicher", "", "Wenn 9x = 6,3; dann ist x = ?", "Lineare Gleichung mit formaler Variable", 60),
 "Zahl gesucht 2": (5, "sicher", "", "Auf welche Zahl zeigt der Pfeil ungefaehr? (Intervall [240 000; 260 000])", "Zahlenstrahl/grosse Zahlen ablesen", 60),
 "Zahlen addieren": (6, "sicher", "", "Die Summe von zwei solchen Bruchzahlen soll 1/8 ergeben (EMF-Text)", "Brueche addieren/zerlegen (Teil 1 nat. Zahlen)", 150),
 "Zahlen gesucht": (5, "unsicher", "5/6", "Schreibe alle dreistelligen Zahlen auf, die aus den Ziffern 1, 2 und 3 gebildet werden koennen.", "Systematisches Zaehlen/Kombinatorik", 90),
 "Zahlenmauer": (5, "sicher", "", "steht in jedem Stein die Summe der beiden darunter liegenden Steine", "Additive Zahlenmauern", 90),
 "Zahlenstrahl": (6, "sicher", "", "Markiere die Zahl 1/5 mit einem Pfeil auf dem gegebenen Zahlenstrahl (EMF-Text)", "Brueche am Zahlenstrahl", 90),
 "Zahlensuche": (5, "sicher", "", "ihr Vorgaenger (die vorangehende natuerliche Zahl) und das Doppelte dieses Vorgaengers", "Natuerliche Zahlen/Vorgaenger, Verdoppeln", 90),
 "Zahlensumme": (8, "unsicher", "5/8", "als Summe aus drei aufeinanderfolgenden natuerlichen Zahlen darstellen", "Zahleigenschaften (5); allgemeines Begruenden per Term (8)", 150),
 "Zahlenwürfel": (6, "sicher", "", "hat 30 gleich grosse Seitenflaechen ... Wahrscheinlichkeit, dass die Zahl 9 geworfen wird", "Laplace-Wahrscheinlichkeit + Unabhaengigkeits-Argument", 210),
 "Zeitangabe": (5, "sicher", "", "Wie viele Minuten sind 2½ Stunden?", "Zeiteinheiten umrechnen", 45),
 "Zeitumrechnung": (6, "sicher", "", "die Zeit als Dezimalzahl in Stunden anzugeben", "Dezimalzahlen/Zeitgroessen", 90),
 "Zoobesuch": (7, "unsicher", "7/8", "Welches Diagramm passt am besten zu diesem Vorgang?", "Qualitativer Graph zu Sachsituation", 75),
 "Zufallsversuche": (6, "sicher", "", "Mit einem 12-seitigen Spielwuerfel werden Zufallsversuche durchgefuehrt.", "Laplace-Wahrscheinlichkeit einstufig", 90),
 "Zuschauerzahlen": (5, "sicher", "", "Runde diese Zahl auf Tausender. (EMF-Text)", "Runden/Ueberschlag grosser Zahlen", 150),
 "Zwanzig Prozent": (7, "sicher", "", "Gib 20% von 150€ an.", "Prozentwert berechnen", 45),
 "Zwei Kreise": (7, "unsicher", "7/8", "Beide Kreise haben den gleichen Radius r = |AB|.", "Gleichseitige/gleichschenklige Dreiecke, Winkel- und Flaechenargumente", 240),
 "Zwei Taschenrechner": (7, "sicher", "", "Werbeaktion: 20 % mehr zum gleichen Preis.", "Prozentrechnung (Prozenttaste verstehen)", 120),
 "Zwei Thermometeranzeigen": (7, "unsicher", "5/7", "Das linke Thermometer zeigt die Temperatur, die morgens gemessen wurde.", "Temperaturdifferenz — vermutlich mit negativen Zahlen (Bild noetig)", 90),
 "Zweite Gerade": (8, "sicher", "", "eine zweite Gerade ein, die eine groessere Steigung ... hat", "Lineare Funktionen (Steigung)", 75),
 "Zwischen zwei Zahlen": (6, "sicher", "", "Welche der folgenden Zahlen liegt zwischen 0,06 und 0,07?", "Dezimalzahlen ordnen", 45),
 "Zwischen zwei Zahlen 2": (7, "sicher", "", "zwei unterschiedliche rationale Zahlen aus dem Intervall ]-4,5; -3,5[ (Auswertung)", "Negative rationale Zahlen ordnen/angeben", 60),
 "Zählung von Fahrzeugen": (5, "unsicher", "5/6", "hat 500 Fahrzeuge beobachtet und gezaehlt ... in folgender Tabelle dargestellt", "Daten/Tabelle auswerten; eigentliche Frage fehlt", 120),
 "Überschlag doch mal": (5, "sicher", "", "wie viele Unterrichtsstunden es in acht Schuljahren wohl schon waren", "Ueberschlagsrechnung", 75),
 "Überschlagsrechnung": (5, "sicher", "", "Das Ergebnis von 91 · 88 soll durch eine Ueberschlagsrechnung ... ermittelt werden.", "Ueberschlagsrechnung/Runden", 45),
}
